// Auto-generated by tools/decompose.mjs — edit freely after generation
// Module: js/core/constants.js

export const COLORS=["#00cfff","#ff6b35","#7fff2a","#ff3dff","#ffe600","#00ff9f","#bf5fff"];

export const FALLBACK_DIRS=[[0.940,0.000,0.342],[0.552,0.760,-0.342],[-0.210,0.916,0.342],[-0.846,0.411,-0.342],[-0.846,-0.411,0.342],[-0.210,-0.916,-0.342],[0.552,-0.760,0.342]];

export const DEFAULT_DISCS=["Thermodynamics / Physics","Neuroscience / Cognitive Science","Philosophy / Metaphysics","Biology / Evolution","Mathematics / Information Theory","Sociology / Anthropology","Computer Science / AI"];

export const TYPE_CFG={unique:{label:"UNIQUE",col:"#666",desc:"one discipline only"},convergent:{label:"CONVERGENT",col:"#99aaff",desc:"shared across 2+ disciplines"},contradictory:{label:"CONTRADICTORY",col:"#ff9500",desc:"tension between disciplines"},emergent:{label:"EMERGENT",col:"#ffd700",desc:"synthesis only"}};

export const TYPE_PRIORITY={unique:1,convergent:2,contradictory:3,emergent:4};

export const QUALITY_PROFILES={
  fast:{id:"fast",probeTermMin:6,probeTermMax:8,synthConvergent:"2-4",synthContradictory:"1-3",synthEmergent:"2-3",temperature:0.15,maxTokens:1000,embedBatchSize:36,cleanup:false},
  balanced:{id:"balanced",probeTermMin:8,probeTermMax:10,synthConvergent:"3-6",synthContradictory:"2-4",synthEmergent:"3-5",temperature:0.2,maxTokens:1400,embedBatchSize:24,cleanup:false},
  rigor:{id:"rigor",probeTermMin:10,probeTermMax:14,synthConvergent:"4-8",synthContradictory:"3-6",synthEmergent:"4-7",temperature:0.1,maxTokens:1900,embedBatchSize:16,cleanup:true}
};

export const API_ENDPOINTS={direct:{chat:"https://openrouter.ai/api/v1/chat/completions",embeddings:"https://openrouter.ai/api/v1/embeddings"},proxy:{chat:"/api/llm/chat/completions",embeddings:"/api/llm/embeddings"}};

export const PROJECTION_BASE_SEED=20260218;

export const PROJECTION_STABILITY_RUNS=4;

export const SIDEBAR_WIDTH_STORAGE_KEY="parallax_sidebar_width_px";

export const SIDEBAR_WIDTH_DEFAULT=320;

export const SIDEBAR_WIDTH_MIN=250;

export const SIDEBAR_WIDTH_MAX=620;

export const GENERATION_WORKBENCH_WIDTH_STORAGE_KEY="parallax_generation_workbench_left_px";

export const GENERATION_WORKBENCH_LEFT_MIN=320;

export const GENERATION_WORKBENCH_RIGHT_MIN=320;

export const SOURCE_TYPE_LABELS={
  "peer-reviewed":"Peer-reviewed",
  "preprint":"Preprint",
  "gov/ngo":"Government/NGO",
  "major journalism":"Major journalism",
  "blog/opinion":"Blog/opinion",
  "social":"Social",
  "reference":"Reference",
  "computational":"Computational",
  "api":"API",
  "untyped":"Untyped"
};
