// Auto-generated by tools/decompose.mjs — edit freely after generation
// Source: ruliad_expedition_v1.1.html
// Module: js/core/refs.js

export const discInputsEl=document.getElementById("disc-inputs");

export const setupEl=document.getElementById("setup");

export const plotPanelEl=document.getElementById("plot-panel");

export const progressEl=document.getElementById("progress");

export const vizEl=document.getElementById("viz");

export const generatorTabBtn=document.getElementById("tab-generator-btn");

export const plotTabBtn=document.getElementById("tab-plot-btn");

export const TAB_ORDER=[generatorTabBtn,plotTabBtn].filter(Boolean);

export const themeSelectGlobalEl=document.getElementById("theme-select-global");

// All refs are const DOM nodes — no setters needed; importers receive the live binding.
