// Auto-generated by tools/decompose.mjs — edit freely after generation
// Source: ruliad_expedition_v1.1.html
// Module: js/core/state.js

export let DISCS=[];

export let TERMS=[];

export let activeSlices=new Set();

export let activeTypes=new Set();

export let showSurfaces=true;

export let surfaceOpacity=0.09;

export let plotInited=false;

export let sessionConfig=null;

export let umapModulePromise=null;

export let nodeColorMode="type";

export let showGroundingOverlays=true;

export let LAST_RUN=null;

export let activeTab="generator";

export let isGenerating=false;

export let lastReportText="";

export let lastClaimsText="";

export let lastOutlineText="";

export let lastCritiqueText="";

export let lastMarkdownText="";

export let zenModeEnabled=false;

export let CALL_LOGS=[];

export let RUN_STATE=null;

export let CITATIONS=[];

export let CURRENT_RUN_ID=null;

export let CITATION_UNMAPPED_SUPPORTING_TERMS=[];

export let DISC_SIM_MATRIX=null;

export let PROJECTION_STABILITY=null;

export let CA_PROBE_OUTPUT=null;

export let WOLFRAM_GROUNDING_DIAGNOSTICS=[];

export let AMBIGUITY_QUEUE=[];

export let EVIDENCE_FILTER_STATE={sourceType:"all",termLabel:"",provider:"all"};

export const WOLFRAM_QUERY_CACHE_MEM=new Map();

export const WOLFRAM_TERM_CACHE_MEM=new Map();

export let WOLFRAM_CACHE_STORAGE_ENABLED=true;

export let WOLFRAM_CACHE_LAST_SAVE=0;

export let PROMPT_TEMPLATE_OVERRIDES={};

export let PROMPT_PREVIEW_RENDERING=false;

export let ARTIFACT_STORE={};

export let ARTIFACT_BUSY=false;

export let ACTIVE_ARTIFACT_KEY="";

export let ACTIVE_MODAL_ID="";

// Hybrid compatibility: modules import via export, legacy call-sites use window.*
// Remove once all modules import directly from this file.
Object.assign(window, { DISCS, TERMS, activeSlices, activeTypes, showSurfaces, surfaceOpacity, plotInited, sessionConfig, umapModulePromise, nodeColorMode, showGroundingOverlays, LAST_RUN, activeTab, isGenerating, lastReportText, lastClaimsText, lastOutlineText, lastCritiqueText, lastMarkdownText, zenModeEnabled, CALL_LOGS, RUN_STATE, CITATIONS, CURRENT_RUN_ID, CITATION_UNMAPPED_SUPPORTING_TERMS, DISC_SIM_MATRIX, PROJECTION_STABILITY, CA_PROBE_OUTPUT, WOLFRAM_GROUNDING_DIAGNOSTICS, AMBIGUITY_QUEUE, EVIDENCE_FILTER_STATE, WOLFRAM_QUERY_CACHE_MEM, WOLFRAM_TERM_CACHE_MEM, WOLFRAM_CACHE_STORAGE_ENABLED, WOLFRAM_CACHE_LAST_SAVE, PROMPT_TEMPLATE_OVERRIDES, PROMPT_PREVIEW_RENDERING, ARTIFACT_STORE, ARTIFACT_BUSY, ACTIVE_ARTIFACT_KEY, ACTIVE_MODAL_ID });
