// Auto-generated by tools/decompose.mjs — edit freely after generation
// Source: ruliad_expedition_v1.1.html
// Module: js/core/state.js

export let DISCS=[];

export let TERMS=[];

export let activeSlices=new Set();

export let activeTypes=new Set();

export let plotInited=false;

export let sessionConfig=null;

export let umapModulePromise=null;

export let nodeColorMode="type";

export let showGroundingOverlays=true;

export let LAST_RUN=null;

export let activeTab="generator";

export let isGenerating=false;

export let lastReportText="";

export let lastClaimsText="";

export let lastOutlineText="";

export let lastCritiqueText="";

export let lastMarkdownText="";

export let zenModeEnabled=false;

export let CALL_LOGS=[];

export let RUN_STATE=null;

export let CITATIONS=[];

export let CURRENT_RUN_ID=null;

export let CITATION_UNMAPPED_SUPPORTING_TERMS=[];

export let DISC_SIM_MATRIX=null;

export let PROJECTION_STABILITY=null;

export let CA_PROBE_OUTPUT=null;

export let SEMANTIC_EDGES=null;

export let EVIDENCE_FILTER_STATE={sourceType:"all",termLabel:""};

export let PROMPT_TEMPLATE_OVERRIDES={};

export let PROMPT_PREVIEW_RENDERING=false;

export let ARTIFACT_STORE={};

export let ARTIFACT_BUSY=false;

export let ACTIVE_ARTIFACT_KEY="";

export let ACTIVE_MODAL_ID="";

export let SOURCE_MATERIAL={urls:[],text:"",titles:[],byDisc:{}};

// Setters — the only way to reassign these bindings from outside this module.
// ES modules create read-only live bindings for importers; reassignment must
// happen inside the defining module via these closures.
export const setDiscs = v => { DISCS = v; };
export const setTerms = v => { TERMS = v; };
export const setActiveSlices = v => { activeSlices = v; };
export const setActiveTypes = v => { activeTypes = v; };
export const setPlotInited = v => { plotInited = v; };
export const setSessionConfig = v => { sessionConfig = v; };
export const setUmapModulePromise = v => { umapModulePromise = v; };
export const setNodeColorMode = v => { nodeColorMode = v; };
export const setShowGroundingOverlays = v => { showGroundingOverlays = v; };
export const setLastRun = v => { LAST_RUN = v; };
export const setActiveTab = v => { activeTab = v; };
export const setIsGenerating = v => { isGenerating = v; };
export const setLastReportText = v => { lastReportText = v; };
export const setLastClaimsText = v => { lastClaimsText = v; };
export const setLastOutlineText = v => { lastOutlineText = v; };
export const setLastCritiqueText = v => { lastCritiqueText = v; };
export const setLastMarkdownText = v => { lastMarkdownText = v; };
export const setZenModeEnabled = v => { zenModeEnabled = v; };
export const setCallLogs = v => { CALL_LOGS = v; };
export const setRunState = v => { RUN_STATE = v; };
export const setCitations = v => { CITATIONS = v; };
export const setCurrentRunId = v => { CURRENT_RUN_ID = v; };
export const setCitationUnmappedSupportingTerms = v => { CITATION_UNMAPPED_SUPPORTING_TERMS = v; };
export const setDiscSimMatrix = v => { DISC_SIM_MATRIX = v; };
export const setProjectionStability = v => { PROJECTION_STABILITY = v; };
export const setCAProbeOutput = v => { CA_PROBE_OUTPUT = v; };
export const setSemanticEdges = v => { SEMANTIC_EDGES = v; };
export const setEvidenceFilterState = v => { EVIDENCE_FILTER_STATE = v; };
export const setPromptPreviewRendering = v => { PROMPT_PREVIEW_RENDERING = v; };
export const setArtifactStore = v => { ARTIFACT_STORE = v; };
export const setArtifactBusy = v => { ARTIFACT_BUSY = v; };
export const setActiveArtifactKey = v => { ACTIVE_ARTIFACT_KEY = v; };
export const setActiveModalId = v => { ACTIVE_MODAL_ID = v; };
export const setPromptTemplateOverrides = v => { PROMPT_TEMPLATE_OVERRIDES = v; };
export const setSourceMaterial = v => { SOURCE_MATERIAL = v; };
