import { umapModulePromise, setUmapModulePromise } from '../core/state.js';

// Auto-generated by tools/decompose.mjs — edit freely after generation
// Module: js/embedding/umap-loader.js

export function loadUMAPModule(){if(!umapModulePromise){setUmapModulePromise(import("https://esm.sh/umap-js@1.4.0").then(mod=>{if(!mod||!mod.UMAP) throw new Error("UMAP export not found");return mod;}));}return umapModulePromise;}
