import { GENERATION_WORKBENCH_WIDTH_STORAGE_KEY, SIDEBAR_WIDTH_DEFAULT } from '../core/constants.js';
import { ACTIVE_ARTIFACT_KEY, activeTab, plotInited, setNodeColorMode, setShowGroundingOverlays } from '../core/state.js';
import { discInputsEl, themeSelectGlobalEl } from '../core/refs.js';
import { loadWolframCaches } from '../core/storage.js';
import { initTabAccessibility, switchMainTab, toggleZenMode } from './tabs.js';
import { applyTheme } from './theme.js';
import { addProbeSpec, clearApiKey, generateOrthogonalLenses, initGenerationPanelQol, initWorkbenchJumpNav, onProbeActionClick, renderDisciplineInputs, syncApiModeNote, syncCAOverrideUI, toggleApiKey } from './setup-panel.js';
import { applyGenerationWorkbenchLeftWidth, applySidebarWidth, initGenerationWorkbenchResizer, initSidebarResizer } from './resizers.js';
import { closeModal, handleModalKeyboard } from './modals.js';
import { updateAmbiguityQueueUIState } from './notifications.js';
import { applyPromptPreviewOverride, refreshPromptPreview, resetPromptPreviewOverride, syncPromptPreviewDiscOptions } from './prompt-preview.js';
import { onAmbiguityQueueClick, showAmbiguityQueueModal } from './ambiguity-queue-ui.js';
import { showEvidenceModal } from './evidence-modal-ui.js';
import { openArtifact, refreshArtifactList, setArtifactDrawer, setExportMenu, toggleArtifactDrawer, toggleExportMenu } from './artifact-drawer-ui.js';
import { launchExpedition, resetToSetup } from '../pipeline/launch-expedition.js';
import { rerunSynthesis } from '../pipeline/reruns.js';
import { renderPlot } from '../plot/plot-render.js';
import { initNodeFilterControls, renderGroundingLegend } from '../plot/sidebar.js';
import { initArtifactStore, markArtifactsStale } from '../artifacts/artifact-store.js';
import { copyActiveArtifact, copyClaimsText, copyCritiqueText, copyOutlineText, copyReportText, downloadActiveArtifact, downloadArtifact, generateClaimsLedger, generateDeepReport, generateOutlineFromMap, runRedTeamPass, runReplication, showRawNodeList } from '../artifacts/artifact-generators.js';
import { exportArtifactBundle, exportFigure, exportMarkdownReport, exportRunToFile } from '../artifacts/exporters.js';
import { exportWAGraphReadyArtifacts } from '../artifacts/wa-graph-export.js';
import { importRunFromFile } from '../io/import-export-run.js';

// Auto-generated by tools/decompose.mjs — edit freely after generation
// Source: ruliad_expedition_v1.1.html
// Module: js/ui/bootstrap.js

loadWolframCaches();

renderDisciplineInputs(7);

initGenerationPanelQol();

initSidebarResizer();

initGenerationWorkbenchResizer();

initWorkbenchJumpNav();

document.getElementById("launch-btn").addEventListener("click",launchExpedition);

document.getElementById("reset-btn").addEventListener("click",resetToSetup);

document.getElementById("clear-btn").addEventListener("click",()=>{document.getElementById("detail").style.display="none";});

document.getElementById("toggle-key-btn").addEventListener("click",toggleApiKey);

document.getElementById("clear-key-btn").addEventListener("click",clearApiKey);

document.getElementById("gen-lenses-btn").addEventListener("click",generateOrthogonalLenses);

if(themeSelectGlobalEl){themeSelectGlobalEl.addEventListener("change",e=>{applyTheme(e.target.value,true);});}

initTabAccessibility();

initNodeFilterControls();

document.getElementById("node-color-mode-select").addEventListener("change",e=>{setNodeColorMode(e.target.value==="grounding"?"grounding":"type");renderGroundingLegend();if(plotInited&&activeTab==="plot"){renderPlot();}});

document.getElementById("grounding-overlay-check").addEventListener("change",e=>{setShowGroundingOverlays(Boolean(e.target.checked));renderGroundingLegend();if(plotInited&&activeTab==="plot"){renderPlot();}});

renderGroundingLegend();

document.getElementById("export-run-btn").addEventListener("click",exportRunToFile);

document.getElementById("import-run-btn").addEventListener("click",()=>document.getElementById("run-file-input").click());

document.getElementById("run-file-input").addEventListener("change",importRunFromFile);

document.getElementById("add-probe-btn").addEventListener("click",addProbeSpec);

discInputsEl.addEventListener("click",onProbeActionClick);

document.getElementById("target-input").addEventListener("input",()=>{markArtifactsStale(["claims","outline","deep_report","red_team","replication","markdown"]);refreshPromptPreview();});

discInputsEl.addEventListener("input",()=>{markArtifactsStale(["claims","outline","deep_report","red_team","replication","markdown"]);syncPromptPreviewDiscOptions();refreshPromptPreview();});

discInputsEl.addEventListener("change",()=>{syncPromptPreviewDiscOptions();refreshPromptPreview();});

for(const id of ["api-mode","quality-mode-select","redteam-check","source-policy-input","replication-models-input","replication-runs-input","replication-strategy-select","research-model-input","embedding-model-input","web-search-check","wolfram-grounding-check","wolfram-appid-input","grounding-mode-select","grounding-min-score-input","grounding-min-alignment-score-input","grounding-annotate-only-check","grounding-allow-category-mismatch-check","ca-probe-check","ca-rule-input","ca-steps-input","ca-width-input","prompt-intent-input","prompt-lens-emphasis-input","prompt-hard-constraints-input","prompt-output-style-input","prompt-artifact-focus-input"]){const el=document.getElementById(id);if(!el) continue;const onChange=()=>{markArtifactsStale(["claims","outline","deep_report","red_team","replication","markdown"]);refreshPromptPreview();};el.addEventListener("change",onChange);el.addEventListener("input",onChange);}

for(const id of ["prompt-preview-kind-select","prompt-preview-disc-select","lens-count-input"]){const el=document.getElementById(id);if(!el) continue;const onPreview=()=>{refreshPromptPreview();};el.addEventListener("change",onPreview);el.addEventListener("input",onPreview);}

document.getElementById("prompt-preview-refresh-btn").addEventListener("click",refreshPromptPreview);

document.getElementById("prompt-preview-apply-btn").addEventListener("click",applyPromptPreviewOverride);

document.getElementById("prompt-preview-reset-btn").addEventListener("click",resetPromptPreviewOverride);

document.getElementById("prompt-preview-discard-btn").addEventListener("click",refreshPromptPreview);

document.getElementById("raw-list-btn").addEventListener("click",showRawNodeList);

document.getElementById("evidence-btn").addEventListener("click",showEvidenceModal);

document.getElementById("ambiguity-btn").addEventListener("click",showAmbiguityQueueModal);

document.getElementById("claims-btn").addEventListener("click",generateClaimsLedger);

document.getElementById("redteam-btn").addEventListener("click",runRedTeamPass);

document.getElementById("replication-btn").addEventListener("click",runReplication);

document.getElementById("outline-btn").addEventListener("click",generateOutlineFromMap);

document.getElementById("export-md-btn").addEventListener("click",exportMarkdownReport);

document.getElementById("export-fig-btn").addEventListener("click",exportFigure);

document.getElementById("rerun-synth-btn").addEventListener("click",rerunSynthesis);

document.getElementById("raw-close-btn").addEventListener("click",()=>closeModal("raw-modal"));

document.getElementById("deep-report-btn").addEventListener("click",generateDeepReport);

document.getElementById("report-close-btn").addEventListener("click",()=>closeModal("report-modal"));

document.getElementById("report-copy-btn").addEventListener("click",copyReportText);

document.getElementById("evidence-close-btn").addEventListener("click",()=>closeModal("evidence-modal"));

document.getElementById("ambiguity-close-btn").addEventListener("click",()=>closeModal("ambiguity-modal"));

document.getElementById("claims-close-btn").addEventListener("click",()=>closeModal("claims-modal"));

document.getElementById("claims-copy-btn").addEventListener("click",copyClaimsText);

document.getElementById("outline-close-btn").addEventListener("click",()=>closeModal("outline-modal"));

document.getElementById("outline-copy-btn").addEventListener("click",copyOutlineText);

document.getElementById("critique-close-btn").addEventListener("click",()=>closeModal("critique-modal"));

document.getElementById("critique-copy-btn").addEventListener("click",copyCritiqueText);

document.getElementById("replication-close-btn").addEventListener("click",()=>closeModal("replication-modal"));

document.getElementById("artifacts-btn").addEventListener("click",toggleArtifactDrawer);

document.getElementById("artifact-drawer-close").addEventListener("click",()=>setArtifactDrawer(false));

document.getElementById("artifact-rerun-synth-btn").addEventListener("click",async()=>{setArtifactDrawer(false);await rerunSynthesis();markArtifactsStale(["claims","outline","deep_report","red_team","replication","markdown"]);refreshArtifactList();});

document.getElementById("new-run-btn").addEventListener("click",resetToSetup);

document.getElementById("zen-mode-btn").addEventListener("click",toggleZenMode);

document.getElementById("export-menu-btn").addEventListener("click",toggleExportMenu);

document.getElementById("export-menu-figure").addEventListener("click",async()=>{setExportMenu(false);await exportFigure();});

document.getElementById("export-menu-markdown").addEventListener("click",async()=>{setExportMenu(false);await openArtifact("markdown",{regenerate:true,openAfter:false});await downloadArtifact("markdown");});

document.getElementById("export-menu-wa-graph").addEventListener("click",async()=>{setExportMenu(false);await exportWAGraphReadyArtifacts();});

document.getElementById("export-menu-bundle").addEventListener("click",async()=>{setExportMenu(false);await exportArtifactBundle();});

document.getElementById("artifact-close-btn").addEventListener("click",()=>closeModal("artifact-modal"));

document.getElementById("artifact-copy-btn").addEventListener("click",copyActiveArtifact);

document.getElementById("artifact-download-btn").addEventListener("click",downloadActiveArtifact);

document.getElementById("artifact-regenerate-btn").addEventListener("click",async()=>{if(!ACTIVE_ARTIFACT_KEY) return;await openArtifact(ACTIVE_ARTIFACT_KEY,{regenerate:true,openAfter:true});});

for(const modalId of ["raw-modal","report-modal","evidence-modal","ambiguity-modal","claims-modal","outline-modal","critique-modal","replication-modal"]){document.getElementById(modalId).addEventListener("click",e=>{if(e.target.id===modalId) closeModal(modalId);});}

document.getElementById("artifact-modal").addEventListener("click",e=>{if(e.target.id==="artifact-modal") closeModal("artifact-modal");});

document.getElementById("ambiguity-modal-content").addEventListener("click",onAmbiguityQueueClick);

document.addEventListener("keydown",handleModalKeyboard);

document.addEventListener("click",e=>{const menu=document.getElementById("export-menu");const btn=document.getElementById("export-menu-btn");if(!menu.classList.contains("open")) return;if(e.target===btn||btn.contains(e.target)||menu.contains(e.target)) return;setExportMenu(false);});

document.getElementById("api-mode").addEventListener("change",syncApiModeNote);

syncApiModeNote();

document.getElementById("ca-probe-check")?.addEventListener("change",syncCAOverrideUI);

syncCAOverrideUI();

updateAmbiguityQueueUIState();

window.addEventListener("resize",()=>{
  const raw=getComputedStyle(document.documentElement).getPropertyValue("--sidebar-width").replace("px","").trim();
  const width=Number(raw);
  applySidebarWidth(Number.isFinite(width)?width:SIDEBAR_WIDTH_DEFAULT,{persist:true});
  const wbRaw=Number(sessionStorage.getItem(GENERATION_WORKBENCH_WIDTH_STORAGE_KEY));
  if(Number.isFinite(wbRaw)) applyGenerationWorkbenchLeftWidth(wbRaw,{persist:true});
  if(plotInited&&activeTab==="plot"){try{Plotly.Plots.resize(document.getElementById("plot"));}catch{}}
});

applyTheme(sessionStorage.getItem("ruliad_theme")||"light",false);

switchMainTab("generator",{silent:true,focusTarget:false});

initArtifactStore();

syncPromptPreviewDiscOptions();

refreshPromptPreview();
