import { GENERATION_WORKBENCH_WIDTH_STORAGE_KEY } from '../core/constants.js';
import { ACTIVE_ARTIFACT_KEY, activeTab, galleryActive, plotInited, setNodeColorMode } from '../core/state.js';
import { toggleGallery } from '../plot/gallery.js';
import { discInputsEl, themeSelectGlobalEl } from '../core/refs.js';
import { initTabAccessibility, switchMainTab, toggleZenMode } from './tabs.js';
import { applyTheme } from './theme.js';
import { addProbeSpec, clearApiKey, clearSources, findStories, generateOrthogonalLenses, initGenerationPanelQol, initProgressiveDisclosure, initSourcesPanel, initWorkbenchJumpNav, launchLensRun, onProbeActionClick, renderDisciplineInputs, syncApiModeNote, syncCAOverrideUI, toggleApiKey } from './setup-panel.js';
import { applyGenerationWorkbenchLeftWidth, initGenerationWorkbenchResizer } from './resizers.js';
import { closeModal, handleModalKeyboard } from './modals.js';
import { applyPromptPreviewOverride, refreshPromptPreview, resetPromptPreviewOverride, syncPromptPreviewDiscOptions } from './prompt-preview.js';
import { showEvidenceModal } from './evidence-modal-ui.js';
import { openArtifact, refreshArtifactList, setArtifactDrawer, setExportMenu, toggleArtifactDrawer, toggleExportMenu } from './artifact-drawer-ui.js';
import { launchExpedition, resetToSetup } from '../pipeline/launch-expedition.js';
import { rerunSynthesis } from '../pipeline/reruns.js';
import { renderPlot } from '../plot/plot-render.js';
import { initNodeFilterControls, renderGroundingLegend } from '../plot/sidebar.js';
import { initArtifactStore, markArtifactsStale } from '../artifacts/artifact-store.js';
import { copyActiveArtifact, copyClaimsText, copyCritiqueText, copyOutlineText, copyReportText, downloadActiveArtifact, downloadArtifact, generateClaimsLedger, generateDeepReport, generateOutlineFromMap, runRedTeamPass, runReplication, showRawNodeList } from '../artifacts/artifact-generators.js';
import { exportArtifactBundle, exportFigure, exportMarkdownReport, exportRunToFile } from '../artifacts/exporters.js';
import { importRunFromFile, loadSampleRun } from '../io/import-export-run.js';
import { setHistoryDrawer, toggleHistoryDrawer } from './history-drawer-ui.js';

// Auto-generated by tools/decompose.mjs — edit freely after generation
// Module: js/ui/bootstrap.js

renderDisciplineInputs(7);

initGenerationPanelQol();

initProgressiveDisclosure();

initSourcesPanel();

initGenerationWorkbenchResizer();

initWorkbenchJumpNav();

document.getElementById("launch-btn").addEventListener("click",launchExpedition);

document.getElementById("reset-btn").addEventListener("click",resetToSetup);


document.getElementById("toggle-key-btn").addEventListener("click",toggleApiKey);

document.getElementById("clear-key-btn").addEventListener("click",clearApiKey);

document.getElementById("gen-lenses-btn").addEventListener("click",generateOrthogonalLenses);

document.getElementById("find-stories-btn")?.addEventListener("click",findStories);

document.getElementById("source-article-close-btn")?.addEventListener("click",()=>{const m=document.getElementById("source-article-modal");if(m){m.classList.remove("open");m.style.display="";}});

document.getElementById("source-article-modal")?.addEventListener("click",e=>{if(e.target.id==="source-article-modal"){const m=e.target;m.classList.remove("open");m.style.display="";}});

document.getElementById("use-sources-btn")?.addEventListener("click",launchLensRun);

document.getElementById("clear-sources-btn")?.addEventListener("click",clearSources);

if(themeSelectGlobalEl){themeSelectGlobalEl.addEventListener("change",e=>{applyTheme(e.target.value,true);});}

initTabAccessibility();

initNodeFilterControls();

document.getElementById("node-color-mode-select").addEventListener("change",e=>{setNodeColorMode(e.target.value);renderGroundingLegend();if(plotInited&&activeTab==="plot"&&!galleryActive){renderPlot();}});

renderGroundingLegend();

document.getElementById("export-run-btn").addEventListener("click",exportRunToFile);

document.getElementById("history-btn").addEventListener("click",toggleHistoryDrawer);
document.getElementById("history-drawer-close").addEventListener("click",()=>setHistoryDrawer(false));

document.getElementById("import-run-btn").addEventListener("click",()=>document.getElementById("run-file-input").click());

document.getElementById("run-file-input").addEventListener("change",importRunFromFile);

document.getElementById("load-example-btn").addEventListener("click",async()=>{
  const filename=document.getElementById("example-run-select")?.value;
  if(!filename) return;
  const btn=document.getElementById("load-example-btn");
  const prev=btn.textContent;
  btn.disabled=true; btn.textContent="LOADING…";
  await loadSampleRun(filename);
  btn.disabled=false; btn.textContent=prev;
});

// Populate example run dropdown dynamically from server
(async()=>{
  const sel=document.getElementById("example-run-select");
  const card=document.getElementById("mode-card-example");
  if(!sel||!card) return;
  try{
    const resp=await fetch("/api/sample-runs");
    const runs=await resp.json();
    if(!runs.length){card.style.display="none";return;}
    sel.innerHTML="";
    for(const r of runs){const opt=document.createElement("option");opt.value=r.filename;opt.textContent=r.label;sel.appendChild(opt);}
  }catch{card.style.display="none";}
})();

document.getElementById("add-probe-btn").addEventListener("click",addProbeSpec);

discInputsEl.addEventListener("click",onProbeActionClick);

document.getElementById("target-input").addEventListener("input",()=>{markArtifactsStale(["claims","outline","deep_report","red_team","replication","markdown"]);refreshPromptPreview();});

discInputsEl.addEventListener("input",()=>{markArtifactsStale(["claims","outline","deep_report","red_team","replication","markdown"]);syncPromptPreviewDiscOptions();refreshPromptPreview();});

discInputsEl.addEventListener("change",()=>{syncPromptPreviewDiscOptions();refreshPromptPreview();});

for(const id of ["api-mode","quality-mode-select","redteam-check","source-policy-input","replication-models-input","replication-runs-input","replication-strategy-select","research-model-input","embedding-model-input","web-search-check","ca-probe-check","ca-rule-input","ca-steps-input","ca-width-input","prompt-intent-input","prompt-lens-emphasis-input","prompt-hard-constraints-input","prompt-output-style-input","prompt-artifact-focus-input"]){const el=document.getElementById(id);if(!el) continue;const onChange=()=>{markArtifactsStale(["claims","outline","deep_report","red_team","replication","markdown"]);refreshPromptPreview();};el.addEventListener("change",onChange);el.addEventListener("input",onChange);}

for(const id of ["prompt-preview-kind-select","prompt-preview-disc-select","lens-count-input"]){const el=document.getElementById(id);if(!el) continue;const onPreview=()=>{refreshPromptPreview();};el.addEventListener("change",onPreview);el.addEventListener("input",onPreview);}

document.getElementById("prompt-preview-refresh-btn").addEventListener("click",refreshPromptPreview);

document.getElementById("prompt-preview-apply-btn").addEventListener("click",applyPromptPreviewOverride);

document.getElementById("prompt-preview-reset-btn").addEventListener("click",resetPromptPreviewOverride);

document.getElementById("prompt-preview-discard-btn").addEventListener("click",refreshPromptPreview);

document.getElementById("raw-list-btn").addEventListener("click",showRawNodeList);

document.getElementById("evidence-btn").addEventListener("click",showEvidenceModal);

document.getElementById("claims-btn").addEventListener("click",generateClaimsLedger);

document.getElementById("redteam-btn").addEventListener("click",runRedTeamPass);

document.getElementById("replication-btn").addEventListener("click",runReplication);

document.getElementById("outline-btn").addEventListener("click",generateOutlineFromMap);

document.getElementById("export-md-btn").addEventListener("click",exportMarkdownReport);

document.getElementById("export-fig-btn").addEventListener("click",exportFigure);

document.getElementById("rerun-synth-btn").addEventListener("click",rerunSynthesis);

document.getElementById("raw-close-btn").addEventListener("click",()=>closeModal("raw-modal"));

document.getElementById("deep-report-btn").addEventListener("click",generateDeepReport);

document.getElementById("report-close-btn").addEventListener("click",()=>closeModal("report-modal"));

document.getElementById("report-copy-btn").addEventListener("click",copyReportText);

document.getElementById("evidence-close-btn").addEventListener("click",()=>closeModal("evidence-modal"));

document.getElementById("claims-close-btn").addEventListener("click",()=>closeModal("claims-modal"));

document.getElementById("claims-copy-btn").addEventListener("click",copyClaimsText);

document.getElementById("outline-close-btn").addEventListener("click",()=>closeModal("outline-modal"));

document.getElementById("outline-copy-btn").addEventListener("click",copyOutlineText);

document.getElementById("critique-close-btn").addEventListener("click",()=>closeModal("critique-modal"));

document.getElementById("critique-copy-btn").addEventListener("click",copyCritiqueText);

document.getElementById("replication-close-btn").addEventListener("click",()=>closeModal("replication-modal"));

document.getElementById("artifacts-btn").addEventListener("click",toggleArtifactDrawer);

document.getElementById("artifact-drawer-close").addEventListener("click",()=>setArtifactDrawer(false));

document.getElementById("artifact-rerun-synth-btn").addEventListener("click",async()=>{setArtifactDrawer(false);await rerunSynthesis();markArtifactsStale(["claims","outline","deep_report","red_team","replication","markdown"]);refreshArtifactList();});

document.getElementById("new-run-btn").addEventListener("click",resetToSetup);

document.getElementById("gallery-btn").addEventListener("click",toggleGallery);

document.getElementById("zen-mode-btn").addEventListener("click",toggleZenMode);

document.getElementById("export-menu-btn").addEventListener("click",toggleExportMenu);

document.getElementById("export-menu-figure").addEventListener("click",async()=>{setExportMenu(false);await exportFigure();});

document.getElementById("export-menu-markdown").addEventListener("click",async()=>{setExportMenu(false);await openArtifact("markdown",{regenerate:true,openAfter:false});await downloadArtifact("markdown");});

document.getElementById("export-menu-bundle").addEventListener("click",async()=>{setExportMenu(false);await exportArtifactBundle();});

document.getElementById("artifact-close-btn").addEventListener("click",()=>closeModal("artifact-modal"));

document.getElementById("artifact-copy-btn").addEventListener("click",copyActiveArtifact);

document.getElementById("artifact-download-btn").addEventListener("click",downloadActiveArtifact);

document.getElementById("artifact-regenerate-btn").addEventListener("click",async()=>{if(!ACTIVE_ARTIFACT_KEY) return;await openArtifact(ACTIVE_ARTIFACT_KEY,{regenerate:true,openAfter:true});});

for(const modalId of ["raw-modal","report-modal","evidence-modal","claims-modal","outline-modal","critique-modal","replication-modal"]){document.getElementById(modalId).addEventListener("click",e=>{if(e.target.id===modalId) closeModal(modalId);});}

document.getElementById("artifact-modal").addEventListener("click",e=>{if(e.target.id==="artifact-modal") closeModal("artifact-modal");});

document.addEventListener("keydown",handleModalKeyboard);

document.addEventListener("click",e=>{const menu=document.getElementById("export-menu");const btn=document.getElementById("export-menu-btn");if(!menu.classList.contains("open")) return;if(e.target===btn||btn.contains(e.target)||menu.contains(e.target)) return;setExportMenu(false);});

document.getElementById("api-mode").addEventListener("change",syncApiModeNote);

syncApiModeNote();

document.getElementById("ca-probe-check")?.addEventListener("change",syncCAOverrideUI);

syncCAOverrideUI();

window.addEventListener("resize",()=>{
  const wbRaw=Number(sessionStorage.getItem(GENERATION_WORKBENCH_WIDTH_STORAGE_KEY));
  if(Number.isFinite(wbRaw)) applyGenerationWorkbenchLeftWidth(wbRaw,{persist:true});
  if(plotInited&&activeTab==="plot"&&!galleryActive){try{Plotly.Plots.resize(document.getElementById("plot"));}catch{}}
});

applyTheme(sessionStorage.getItem("parallax_theme")||"light",false);

switchMainTab("generator",{silent:true,focusTarget:false});

initArtifactStore();

syncPromptPreviewDiscOptions();

refreshPromptPreview();

// Floating panel open/close helpers
const PANEL_TRIGGER_MAP={"controls-panel":"controls-trigger","diagnostics-panel":"diagnostics-trigger"};
function syncTrigger(panelId,isOpen){const tid=PANEL_TRIGGER_MAP[panelId];if(tid) document.getElementById(tid)?.classList.toggle("panel-open",isOpen);}
function togglePanel(id){const isOpen=document.getElementById(id).classList.toggle("panel-open");syncTrigger(id,isOpen);dismissHintForPanel(id);}
function closePanel(id){document.getElementById(id).classList.remove("panel-open");syncTrigger(id,false);}

function dismissHintForPanel(panelId){
  if(panelId==="controls-panel"&&!sessionStorage.getItem("hint_controls")){
    sessionStorage.setItem("hint_controls","1");
    document.getElementById("controls-hint")?.remove();
    document.getElementById("plot-nav-hint")?.remove();
  }
  if(panelId==="diagnostics-panel"&&!sessionStorage.getItem("hint_diagnostics")){
    sessionStorage.setItem("hint_diagnostics","1");
    document.getElementById("diagnostics-hint")?.remove();
  }
}

// Suppress hints already dismissed in a previous session
if(sessionStorage.getItem("hint_controls")){
  document.getElementById("controls-hint")?.remove();
  document.getElementById("plot-nav-hint")?.remove();
}
if(sessionStorage.getItem("hint_diagnostics")){
  document.getElementById("diagnostics-hint")?.remove();
}

// Panel trigger buttons
document.getElementById("controls-trigger").addEventListener("click",()=>togglePanel("controls-panel"));
document.getElementById("controls-btn").addEventListener("click",()=>togglePanel("controls-panel"));
document.getElementById("diagnostics-trigger").addEventListener("click",()=>togglePanel("diagnostics-panel"));

// X close buttons on all floating panels
document.querySelectorAll(".floating-panel-close").forEach(btn=>{
  btn.addEventListener("click",()=>closePanel(btn.closest(".floating-panel").id));
});
