import { ACTIVE_MODAL_ID } from '../core/state.js';

// Auto-generated by tools/decompose.mjs — edit freely after generation
// Source: ruliad_expedition_v1.1.html
// Module: js/ui/modals.js

export const MODAL_RETURN_FOCUS=new Map();

export const MODAL_FOCUSABLE_SELECTOR=[
  "a[href]",
  "area[href]",
  "input:not([disabled]):not([type='hidden'])",
  "select:not([disabled])",
  "textarea:not([disabled])",
  "button:not([disabled])",
  "iframe",
  "[tabindex]:not([tabindex='-1'])",
  "[contenteditable='true']"
].join(",");

export function isElementVisibleForFocus(el){if(!(el instanceof HTMLElement)) return false;if(el.hidden) return false;const style=getComputedStyle(el);if(style.display==="none"||style.visibility==="hidden") return false;return el.getClientRects().length>0;}

export function getFocusableElementsInModal(modal){if(!modal) return [];const nodes=[...modal.querySelectorAll(MODAL_FOCUSABLE_SELECTOR)];return nodes.filter(el=>el instanceof HTMLElement&&isElementVisibleForFocus(el));}

export function getOpenModals(){return [...document.querySelectorAll(".modal")].filter(el=>el instanceof HTMLElement&&getComputedStyle(el).display!=="none");}

export function getActiveOpenModal(){if(ACTIVE_MODAL_ID){const candidate=document.getElementById(ACTIVE_MODAL_ID);if(candidate&&getComputedStyle(candidate).display!=="none") return candidate;}const open=getOpenModals();return open.length?open[open.length-1]:null;}

export function focusModalEntry(modal){if(!modal) return;const card=modal.querySelector(".modal-card");const focusables=getFocusableElementsInModal(modal);const target=focusables[0]||card||modal;if(target instanceof HTMLElement){if(!target.hasAttribute("tabindex")&&(target===card||target===modal)) target.setAttribute("tabindex","-1");target.focus({preventScroll:true});}}

export function handleModalKeyboard(e){
  const modal=getActiveOpenModal();
  if(!modal) return;
  if(e.key==="Escape"){
    e.preventDefault();
    closeModal(modal.id);
    return;
  }
  if(e.key!=="Tab") return;
  const focusables=getFocusableElementsInModal(modal);
  if(!focusables.length){
    e.preventDefault();
    focusModalEntry(modal);
    return;
  }
  const first=focusables[0];
  const last=focusables[focusables.length-1];
  const active=document.activeElement;
  if(e.shiftKey){
    if(active===first||!modal.contains(active)){e.preventDefault();last.focus();}
    return;
  }
  if(active===last||!modal.contains(active)){e.preventDefault();first.focus();}
}

export function openModal(id){
  const el=document.getElementById(id);
  if(!el) return;
  const wasOpen=getComputedStyle(el).display!=="none";
  const opener=document.activeElement;
  if(!wasOpen&&opener instanceof HTMLElement&&!el.contains(opener)){MODAL_RETURN_FOCUS.set(id,opener);}
  el.style.display="flex";
  ACTIVE_MODAL_ID=id;
  requestAnimationFrame(()=>focusModalEntry(el));
}

export function closeModal(id){
  const el=document.getElementById(id);
  if(!el) return;
  const wasOpen=getComputedStyle(el).display!=="none";
  el.style.display="none";
  if(ACTIVE_MODAL_ID===id){const open=getOpenModals();ACTIVE_MODAL_ID=open.length?open[open.length-1].id:"";}
  const opener=MODAL_RETURN_FOCUS.get(id);
  MODAL_RETURN_FOCUS.delete(id);
  if(wasOpen&&opener instanceof HTMLElement&&document.contains(opener)){requestAnimationFrame(()=>{try{opener.focus({preventScroll:true});}catch{}});}
}
