// Auto-generated by tools/decompose.mjs — edit freely after generation
// Module: js/ui/notifications.js

export function showToast(msg){const t=document.getElementById("toast");t.textContent=msg;t.style.display="block";setTimeout(()=>{t.style.display="none";},5000);}

export function setProbeState(id,state,statusText){const dot=document.getElementById(`dot-${id}`);const status=document.getElementById(`status-${id}`);const item=dot?.closest(".probe-item");if(!dot||!status||!item) return;dot.className=`probe-dot ${state}`;item.className=`probe-item ${state}`;status.textContent=statusText;}
