import { GENERATION_WORKBENCH_LEFT_MIN, GENERATION_WORKBENCH_RIGHT_MIN, GENERATION_WORKBENCH_WIDTH_STORAGE_KEY, SIDEBAR_WIDTH_DEFAULT, SIDEBAR_WIDTH_MAX, SIDEBAR_WIDTH_MIN, SIDEBAR_WIDTH_STORAGE_KEY } from '../core/constants.js';
import { activeTab, plotInited } from '../core/state.js';

// Auto-generated by tools/decompose.mjs — edit freely after generation
// Source: ruliad_expedition_v1.1.html
// Module: js/ui/resizers.js

export function clampSidebarWidth(px){
  const dynamicMax=Math.min(SIDEBAR_WIDTH_MAX,Math.floor((window.innerWidth||1200)*0.62));
  const max=Math.max(SIDEBAR_WIDTH_MIN+40,dynamicMax);
  const n=Number(px);
  if(!Number.isFinite(n)) return Math.min(SIDEBAR_WIDTH_DEFAULT,max);
  return Math.max(SIDEBAR_WIDTH_MIN,Math.min(max,Math.round(n)));
}

export function applySidebarWidth(px,{persist=false}={}){
  const clamped=clampSidebarWidth(px);
  document.documentElement.style.setProperty("--sidebar-width",`${clamped}px`);
  if(persist) sessionStorage.setItem(SIDEBAR_WIDTH_STORAGE_KEY,String(clamped));
  return clamped;
}

export function initSidebarResizer(){
  const vizBody=document.getElementById("viz-body");
  const resizer=document.getElementById("sidebar-resizer");
  if(!vizBody||!resizer) return;
  const saved=Number(sessionStorage.getItem(SIDEBAR_WIDTH_STORAGE_KEY));
  applySidebarWidth(Number.isFinite(saved)?saved:SIDEBAR_WIDTH_DEFAULT,{persist:false});
  let dragging=false;
  const moveWithClientX=(clientX)=>{
    if(!dragging) return;
    const rect=vizBody.getBoundingClientRect();
    applySidebarWidth(clientX-rect.left,{persist:false});
    if(plotInited&&activeTab==="plot"){try{Plotly.Plots.resize(document.getElementById("plot"));}catch{}}
  };
  const startDrag=(clientX)=>{
    if(window.matchMedia("(max-width:900px)").matches) return;
    dragging=true;
    vizBody.classList.add("resizing");
    moveWithClientX(clientX);
  };
  const stopDrag=()=>{
    if(!dragging) return;
    dragging=false;
    vizBody.classList.remove("resizing");
    const raw=getComputedStyle(document.documentElement).getPropertyValue("--sidebar-width").replace("px","").trim();
    const width=Number(raw);
    if(Number.isFinite(width)) sessionStorage.setItem(SIDEBAR_WIDTH_STORAGE_KEY,String(Math.round(width)));
  };
  resizer.addEventListener("mousedown",e=>{e.preventDefault();startDrag(e.clientX);});
  window.addEventListener("mousemove",e=>moveWithClientX(e.clientX));
  window.addEventListener("mouseup",stopDrag);
  resizer.addEventListener("touchstart",e=>{const t=e.touches?.[0];if(!t) return;startDrag(t.clientX);},{passive:true});
  window.addEventListener("touchmove",e=>{const t=e.touches?.[0];if(!t) return;if(dragging) e.preventDefault();moveWithClientX(t.clientX);},{passive:false});
  window.addEventListener("touchend",stopDrag);
  resizer.addEventListener("keydown",e=>{
    if(e.key!=="ArrowLeft"&&e.key!=="ArrowRight") return;
    e.preventDefault();
    const raw=getComputedStyle(document.documentElement).getPropertyValue("--sidebar-width").replace("px","").trim();
    const current=Number.isFinite(Number(raw))?Number(raw):SIDEBAR_WIDTH_DEFAULT;
    const delta=e.key==="ArrowLeft"?-22:22;
    applySidebarWidth(current+delta,{persist:true});
    if(plotInited&&activeTab==="plot"){try{Plotly.Plots.resize(document.getElementById("plot"));}catch{}}
  });
}

export function clampGenerationWorkbenchLeftWidth(px){
  const workbench=document.getElementById("generation-workbench");
  const total=Math.max(760,Math.round(workbench?.getBoundingClientRect?.().width||window.innerWidth||1200));
  const divider=10;
  const max=Math.max(GENERATION_WORKBENCH_LEFT_MIN+120,total-divider-GENERATION_WORKBENCH_RIGHT_MIN);
  const n=Number(px);
  if(!Number.isFinite(n)) return Math.max(GENERATION_WORKBENCH_LEFT_MIN,Math.min(max,Math.round((total-divider)/2)));
  return Math.max(GENERATION_WORKBENCH_LEFT_MIN,Math.min(max,Math.round(n)));
}

export function applyGenerationWorkbenchLeftWidth(px,{persist=false}={}){
  const workbench=document.getElementById("generation-workbench");
  if(!workbench) return null;
  const clamped=clampGenerationWorkbenchLeftWidth(px);
  workbench.style.setProperty("--generation-left-width",`${clamped}px`);
  if(persist) sessionStorage.setItem(GENERATION_WORKBENCH_WIDTH_STORAGE_KEY,String(clamped));
  return clamped;
}

export function initGenerationWorkbenchResizer(){
  const workbench=document.getElementById("generation-workbench");
  const resizer=document.getElementById("workbench-resizer");
  if(!workbench||!resizer) return;
  const saved=Number(sessionStorage.getItem(GENERATION_WORKBENCH_WIDTH_STORAGE_KEY));
  applyGenerationWorkbenchLeftWidth(Number.isFinite(saved)?saved:null,{persist:false});
  let dragging=false;
  const moveWithClientX=(clientX)=>{
    if(!dragging) return;
    const rect=workbench.getBoundingClientRect();
    applyGenerationWorkbenchLeftWidth(clientX-rect.left,{persist:false});
  };
  const startDrag=(clientX)=>{
    if(window.matchMedia("(max-width:700px)").matches) return;
    dragging=true;
    workbench.classList.add("resizing");
    moveWithClientX(clientX);
  };
  const stopDrag=()=>{
    if(!dragging) return;
    dragging=false;
    workbench.classList.remove("resizing");
    const raw=workbench.style.getPropertyValue("--generation-left-width").replace("px","").trim();
    const width=Number(raw);
    if(Number.isFinite(width)) sessionStorage.setItem(GENERATION_WORKBENCH_WIDTH_STORAGE_KEY,String(Math.round(width)));
  };
  resizer.addEventListener("mousedown",e=>{e.preventDefault();startDrag(e.clientX);});
  window.addEventListener("mousemove",e=>moveWithClientX(e.clientX));
  window.addEventListener("mouseup",stopDrag);
  resizer.addEventListener("touchstart",e=>{const t=e.touches?.[0];if(!t) return;startDrag(t.clientX);},{passive:true});
  window.addEventListener("touchmove",e=>{const t=e.touches?.[0];if(!t) return;if(dragging) e.preventDefault();moveWithClientX(t.clientX);},{passive:false});
  window.addEventListener("touchend",stopDrag);
  resizer.addEventListener("keydown",e=>{
    if(e.key!=="ArrowLeft"&&e.key!=="ArrowRight") return;
    e.preventDefault();
    const raw=workbench.style.getPropertyValue("--generation-left-width").replace("px","").trim();
    const current=Number.isFinite(Number(raw))?Number(raw):clampGenerationWorkbenchLeftWidth(null);
    const delta=e.key==="ArrowLeft"?-22:22;
    applyGenerationWorkbenchLeftWidth(current+delta,{persist:true});
  });
}
