import { TERMS, activeTab, isGenerating, plotInited, zenModeEnabled } from '../core/state.js';
import { TAB_ORDER, generatorTabBtn, plotPanelEl, plotTabBtn, progressEl, setupEl, vizEl } from '../core/refs.js';
import { showToast } from './notifications.js';
import { refreshArtifactList, setArtifactDrawer, setExportMenu } from './artifact-drawer-ui.js';
import { renderPlot } from '../plot/plot-render.js';

// Auto-generated by tools/decompose.mjs — edit freely after generation
// Source: ruliad_expedition_v1.1.html
// Module: js/ui/tabs.js

export function updateZenModeUI(){const zenActive=Boolean(zenModeEnabled&&activeTab==="plot"&&!isGenerating);document.body.classList.toggle("plot-zen",zenActive);const btn=document.getElementById("zen-mode-btn");if(btn){btn.textContent=zenActive?"EXIT ZEN":"ZEN MODE";btn.setAttribute("aria-pressed",zenActive?"true":"false");btn.title=zenActive?"Restore top menu and left panel":"Hide top menu and left panel for cinematic capture";}}

export function toggleZenMode(){zenModeEnabled=!zenModeEnabled;updateZenModeUI();if(plotInited&&activeTab==="plot"&&!isGenerating){requestAnimationFrame(()=>{try{Plotly.Plots.resize(document.getElementById("plot"));}catch{}});}}

export function tabNameForButton(btn){if(!btn) return "generator";return btn.id==="tab-plot-btn"?"plot":"generator";}

export function buttonForTabName(name){return name==="plot"?plotTabBtn:generatorTabBtn;}

export function setPanelVisibility(el,visible,displayStyle){if(!el) return;el.hidden=!visible;el.setAttribute("aria-hidden",visible?"false":"true");el.style.display=visible?displayStyle:"none";}

export function updateTabState(activeName){for(const btn of TAB_ORDER){const selected=tabNameForButton(btn)===activeName;btn.classList.toggle("active",selected);btn.setAttribute("aria-selected",selected?"true":"false");btn.tabIndex=selected?0:-1;}}

export function focusTabTarget(activeName){if(activeName==="generator"){const focusEl=document.getElementById("target-input")||setupEl;if(focusEl&&typeof focusEl.focus==="function"){focusEl.focus();}return;}if(isGenerating){progressEl.setAttribute("tabindex","-1");progressEl.focus();return;}const sidebar=document.getElementById("sidebar");if(sidebar&&typeof sidebar.focus==="function"){sidebar.setAttribute("tabindex","-1");sidebar.focus();return;}const plotEl=document.getElementById("plot");if(plotEl&&typeof plotEl.focus==="function"){plotEl.setAttribute("tabindex","-1");plotEl.focus();}}

export function moveTabFocus(currentBtn,delta){const idx=TAB_ORDER.indexOf(currentBtn);if(idx===-1||!TAB_ORDER.length) return;const next=(idx+delta+TAB_ORDER.length)%TAB_ORDER.length;TAB_ORDER[next]?.focus();}

export function initTabAccessibility(){for(const btn of TAB_ORDER){btn.addEventListener("click",()=>switchMainTab(tabNameForButton(btn),{focusTarget:true}));btn.addEventListener("keydown",e=>{if(e.key==="ArrowRight"){e.preventDefault();moveTabFocus(btn,1);return;}if(e.key==="ArrowLeft"){e.preventDefault();moveTabFocus(btn,-1);return;}if(e.key==="Home"){e.preventDefault();TAB_ORDER[0]?.focus();return;}if(e.key==="End"){e.preventDefault();TAB_ORDER[TAB_ORDER.length-1]?.focus();return;}if(e.key==="Enter"||e.key===" "){e.preventDefault();switchMainTab(tabNameForButton(btn),{focusTarget:true});}});}}

export function switchMainTab(tab,{silent=false,focusTarget=true}={}){const target=tab==="plot"?"plot":"generator";if(target==="plot"&&!isGenerating&&!plotInited&&!TERMS.length){if(!silent) showToast("No plot yet. Launch an expedition first.");return;}activeTab=target;updateTabState(activeTab);if(activeTab==="generator"){setPanelVisibility(setupEl,true,"flex");setPanelVisibility(plotPanelEl,false,"block");setPanelVisibility(progressEl,false,"flex");setPanelVisibility(vizEl,false,"flex");setArtifactDrawer(false);setExportMenu(false);updateZenModeUI();if(focusTarget) focusTabTarget("generator");return;}setPanelVisibility(setupEl,false,"flex");setPanelVisibility(plotPanelEl,true,"block");if(isGenerating){setPanelVisibility(progressEl,true,"flex");setPanelVisibility(vizEl,false,"flex");setArtifactDrawer(false);}else{setPanelVisibility(progressEl,false,"flex");setPanelVisibility(vizEl,true,"flex");refreshArtifactList();if(plotInited){requestAnimationFrame(()=>{try{Plotly.Plots.resize(document.getElementById("plot"));renderPlot();}catch(err){console.warn("Plot resize failed:",err);}});}}updateZenModeUI();if(focusTarget) focusTabTarget("plot");}
