import { plotInited } from '../core/state.js';
import { renderPlot } from '../plot/plot-render.js';

// Auto-generated by tools/decompose.mjs — edit freely after generation
// Source: ruliad_expedition_v1.1.html
// Module: js/ui/theme.js

export function applyTheme(theme,persist){const t=(theme==="dark"||theme==="contrast")?theme:"light";document.documentElement.setAttribute("data-theme",t);for(const id of ["theme-select-global"]){const sel=document.getElementById(id);if(sel&&sel.value!==t) sel.value=t;}if(persist){sessionStorage.setItem("ruliad_theme",t);}if(plotInited){renderPlot();}}
