import { API_ENDPOINTS } from '../core/constants.js';

// Auto-generated by tools/decompose.mjs — edit freely after generation
// Module: js/api/provider.js

export function normalizeMode(cfg){return cfg?.mode==="proxy"?"proxy":"direct";}

export function endpointFor(kind,cfg){const modeCfg=API_ENDPOINTS[normalizeMode(cfg)]||API_ENDPOINTS.direct;return modeCfg[kind];}

export async function providerFetch(kind,body,cfg){const headers={"Content-Type":"application/json"};const mode=normalizeMode(cfg);if(cfg.apiKey){headers["Authorization"]=`Bearer ${cfg.apiKey}`;}if(mode==="direct"){headers["HTTP-Referer"]=location.origin&&location.origin!=="null"?location.origin:"https://parallax.local";headers["X-Title"]="Parallax";}const response=await fetch(endpointFor(kind,cfg),{method:"POST",headers,body:JSON.stringify(body)});if(!response.ok){const raw=(await response.text()).slice(0,500);if(response.status===401&&raw.includes("No cookie auth credentials found")){throw new Error(`${kind} request failed (401): OpenRouter did not receive Authorization. Paste a valid OpenRouter key (sk-or-...), keep mode = direct, and if this page is opened as file:// run it via localhost instead. Raw: ${raw}`);}throw new Error(`${kind} request failed (${response.status}): ${raw}`);}return response.json();}
