import { TYPE_CFG } from '../core/constants.js';
import { DISCS, SEMANTIC_EDGES, TERMS } from '../core/state.js';
import { escapeHtml } from '../core/utils.js';
import { renderEvidenceCardsInto } from '../ui/evidence-modal-ui.js';
import { applyDisplayDescriptionForTerm, normalizeTermDescriptions } from '../domain/terms.js';
import { getLinkedCitationsForTerm } from '../domain/citations.js';
import { getTermSignalModel } from '../domain/grounding-status.js';
import { getVisibleNodeTerms } from './sidebar.js';

// Auto-generated by tools/decompose.mjs — edit freely after generation
// Source: ruliad_expedition_v1.1.html
// Module: js/plot/term-detail.js

export function showTermDetail(term){
  if(!term) return;
  const detail=document.getElementById("detail");
  detail.style.borderColor=(TYPE_CFG[term.type]?.col||"#444")+"44";
  document.getElementById("d-label").textContent=term.label;
  const typeEl=document.getElementById("d-type");
  typeEl.textContent=term.type.toUpperCase();
  typeEl.style.color=TYPE_CFG[term.type]?.col||"var(--text)";
  document.getElementById("d-desc").innerHTML=buildTermDescriptionDetail(term);
  const slicesEl=document.getElementById("d-slices");
  if(term.slices.length){
    slicesEl.innerHTML=term.slices.map(sliceId=>{
      const disc=DISCS[sliceId];
      if(!disc) return "";
      return `<span class="dtag" style="background:${disc.col}22;color:${disc.col};border:1px solid ${disc.col}44">${disc.abbr}</span>`;
    }).join("");
  }else{
    slicesEl.innerHTML="<span style=\"font-size:12px;color:var(--muted);font-style:italic\">synthesis only - not in any single probe</span>";
  }
  const citeEl=document.getElementById("d-citations");
  const linked=getLinkedCitationsForTerm(term);
  renderEvidenceCardsInto(citeEl,linked,{variant:"compact",currentTermLabel:term.label});
  document.getElementById("term-detail-panel").classList.add("panel-open");
}

export function formatProvenanceLine(item){const source=String(item?.source||"unknown").toUpperCase();const impact=String(item?.impact||item?.stage||"").trim();const note=String(item?.note||"").trim();const query=String(item?.query||"").trim();const parts=[`[${source}]`];if(impact) parts.push(impact);if(note) parts.push(note);if(query) parts.push(`query: ${query}`);return parts.join(" | ");}

export function summarizeWhyNodeExists(term,sliceNames){if(term.type==="unique"){return `Unique node from a single probe perspective (${sliceNames[0]||"unlabeled probe"}).`;}if(term.type==="convergent"){return `Convergent node synthesized across ${sliceNames.length||0} probe(s) where similar concepts aligned.`;}if(term.type==="contradictory"){return `Contradictory node marks tension across ${sliceNames.length||0} probe(s) with incompatible claims or frames.`;}if(term.type==="emergent"){return "Emergent node added at synthesis stage; it does not originate from one probe alone.";}return "Node included from probe/synthesis output.";}

export function buildTermDescriptionDetail(term){
  applyDisplayDescriptionForTerm(term,{fallbackDescription:term?.description,fallbackSource:term?.description_source});
  const descriptions=normalizeTermDescriptions(term?.descriptions,{fallbackDescription:term?.description,fallbackSource:term?.description_source,label:term?.label});
  const desc=String(descriptions.displayDescription||term?.description||"").trim();
  const provenance=Array.isArray(term?.description_provenance)?term.description_provenance.slice(0,10):[];
  const linkedCitations=getLinkedCitationsForTerm(term);
  const sliceNames=(Array.isArray(term?.slices)?term.slices:[]).map(i=>DISCS[i]?.name).filter(Boolean);
  const probeCount=sliceNames.length;
  const sourceCount=linkedCitations.length;
  const whyNode=summarizeWhyNodeExists(term,sliceNames);
  const signal=getTermSignalModel(term);
  const relevanceScore=Number(signal.relevanceScore||0).toFixed(2);
  const evidenceScore=Number(signal.evidenceSupportScore||0).toFixed(2);
  const displayReason=String(descriptions.displayDescriptionReason||"").trim();
  const probeLayer=String(descriptions.probeSummary||"").trim();
  const synthesisLayer=String(descriptions.synthesisSummary||"").trim();
  const provenanceRows=provenance.length?provenance.map(item=>`<div style="font-size:12px;color:var(--muted);margin-top:3px">- ${escapeHtml(formatProvenanceLine(item))}</div>`).join(""):`<div style="font-size:12px;color:var(--muted);font-style:italic">No provenance entries</div>`;
  return [
    `<div>${escapeHtml(desc||"No description available.")}</div>`,
    `<div style="font-size:12px;color:var(--muted);margin-top:4px">Display description built from: ${escapeHtml(displayReason||"unspecified")}</div>`,
    probeLayer?`<div style="font-size:12px;color:var(--muted);margin-top:3px"><strong>probeSummary:</strong> ${escapeHtml(probeLayer)}</div>`:"",
    synthesisLayer?`<div style="font-size:12px;color:var(--muted);margin-top:3px"><strong>synthesisSummary:</strong> ${escapeHtml(synthesisLayer)}</div>`:"",
    `<div class="tag-row" style="margin-top:8px"><span class="tag">sources: ${sourceCount}</span><span class="tag">probes mentioning: ${probeCount}</span></div>`,
    `<div class="sec-label" style="margin-top:8px">RELEVANCE AND SUPPORT AXES</div>`,
    `<div style="font-size:12px;color:var(--muted)">Relevance score (internal expedition signal): ${relevanceScore} (${escapeHtml(signal.relevanceBand)}).</div>`,
    `<div style="font-size:12px;color:var(--muted);margin-top:3px">Evidence support score (research citations + probe structure): ${evidenceScore} (${escapeHtml(signal.evidenceBand)}).</div>`,
    `<div style="font-size:12px;color:var(--muted);margin-top:3px">Display description source: ${escapeHtml(signal.displayDescriptionSource||term?.description_source||"unknown")}</div>`,
    `<div class="sec-label" style="margin-top:8px">SOURCE PROVENANCE</div>${provenanceRows}`,
    `<div class="sec-label" style="margin-top:8px">WHY THIS NODE EXISTS</div>`,
    `<div style="font-size:12px;color:var(--muted)">${escapeHtml(whyNode)}</div>`,
    `<div style="font-size:12px;color:var(--muted);margin-top:3px">Probe slices: ${escapeHtml(sliceNames.join(" | ")||"synthesis only")}</div>`,
    `<div style="font-size:12px;color:var(--muted);margin-top:3px">Node class logic: ${escapeHtml(term.type)} (${escapeHtml(TYPE_CFG[term.type]?.desc||"")})</div>`,
    buildRelationshipsSection(term)
  ].filter(Boolean).join("");
}

const REL_TYPE_COLORS={analogical:"#3b82f6",causal:"#22c55e",contradictory:"#ff9500",complementary:"#a855f7",hierarchical:"#6b7280",instantiates:"#00cfff"};

function buildRelationshipsSection(term){
  if(!SEMANTIC_EDGES?.relationships?.length) return "";
  const label=term.label.toLowerCase();
  const connected=SEMANTIC_EDGES.relationships.filter(r=>r.term_a.toLowerCase()===label||r.term_b.toLowerCase()===label);
  if(!connected.length) return "";
  connected.sort((a,b)=>b.strength-a.strength);
  const rows=connected.slice(0,8).map(rel=>{
    const other=rel.term_a.toLowerCase()===label?rel.term_b:rel.term_a;
    const color=REL_TYPE_COLORS[rel.type]||"#888";
    const strengthPct=Math.round(rel.strength*100);
    return `<div style="margin-top:5px;font-size:12px"><span style="color:${color};font-weight:bold">${escapeHtml(rel.type)}</span> <span style="color:var(--text)">\u2194 <strong>${escapeHtml(other)}</strong></span> <span style="color:var(--muted)">(${strengthPct}%)</span><div style="color:var(--muted);font-style:italic;margin-top:2px">${escapeHtml(rel.rationale)}</div></div>`;
  }).join("");
  return `<div class="sec-label" style="margin-top:8px">SEMANTIC RELATIONSHIPS</div>${rows}`;
}

export function onPlotClick(data){
  if(!data.points?.[0]) return;
  const label=data.points[0].text;
  const term=getVisibleNodeTerms().find(t=>t.label===label)||TERMS.find(t=>t.label===label);
  if(!term) return;
  showTermDetail(term);
}
