// tools/module-map.mjs
// Auto-generated symbol → target module manifest.
// Edit this file to reassign symbols before re-running decompose.mjs

export const SYMBOL_MAP = {

  // ── core/constants.js ───────────────────────────────────────────────────────
  COLORS:                              'js/core/constants.js',
  FALLBACK_DIRS:                       'js/core/constants.js',
  DEFAULT_DISCS:                       'js/core/constants.js',
  TYPE_CFG:                            'js/core/constants.js',
  TYPE_PRIORITY:                       'js/core/constants.js',
  QUALITY_PROFILES:                    'js/core/constants.js',
  API_ENDPOINTS:                       'js/core/constants.js',
  PROJECTION_BASE_SEED:                'js/core/constants.js',
  PROJECTION_STABILITY_RUNS:           'js/core/constants.js',
  WOLFRAM_CACHE_VERSION:               'js/core/constants.js',
  WOLFRAM_QUERY_CACHE_TTL_MS:          'js/core/constants.js',
  WOLFRAM_TERM_CACHE_TTL_MS:           'js/core/constants.js',
  WOLFRAM_QUERY_CACHE_MAX:             'js/core/constants.js',
  WOLFRAM_TERM_CACHE_MAX:              'js/core/constants.js',
  WOLFRAM_CACHE_STORAGE_KEY:           'js/core/constants.js',
  SIDEBAR_WIDTH_STORAGE_KEY:           'js/core/constants.js',
  SIDEBAR_WIDTH_DEFAULT:               'js/core/constants.js',
  SIDEBAR_WIDTH_MIN:                   'js/core/constants.js',
  SIDEBAR_WIDTH_MAX:                   'js/core/constants.js',
  GENERATION_WORKBENCH_WIDTH_STORAGE_KEY: 'js/core/constants.js',
  GENERATION_WORKBENCH_LEFT_MIN:       'js/core/constants.js',
  GENERATION_WORKBENCH_RIGHT_MIN:      'js/core/constants.js',
  GROUNDING_MODE_DEFAULTS:             'js/core/constants.js',
  NAME_LIKE_METADATA_ALIGNMENT_MIN:    'js/core/constants.js',
  NAME_LIKE_OVERRIDE_ALIGNMENT_MIN:    'js/core/constants.js',
  NAME_LIKE_OVERRIDE_QUALITY_MIN:      'js/core/constants.js',
  SOURCE_TYPE_LABELS:                  'js/core/constants.js',
  GROUNDING_ELIGIBILITY_VALUES:        'js/core/constants.js',

  // ── core/state.js ────────────────────────────────────────────────────────────
  DISCS:                               'js/core/state.js',
  TERMS:                               'js/core/state.js',
  activeSlices:                        'js/core/state.js',
  activeTypes:                         'js/core/state.js',
  showSurfaces:                        'js/core/state.js',
  surfaceOpacity:                      'js/core/state.js',
  plotInited:                          'js/core/state.js',
  sessionConfig:                       'js/core/state.js',
  umapModulePromise:                   'js/core/state.js',
  nodeColorMode:                       'js/core/state.js',
  showGroundingOverlays:               'js/core/state.js',
  LAST_RUN:                            'js/core/state.js',
  activeTab:                           'js/core/state.js',
  isGenerating:                        'js/core/state.js',
  lastReportText:                      'js/core/state.js',
  lastClaimsText:                      'js/core/state.js',
  lastOutlineText:                     'js/core/state.js',
  lastCritiqueText:                    'js/core/state.js',
  lastMarkdownText:                    'js/core/state.js',
  zenModeEnabled:                      'js/core/state.js',
  CALL_LOGS:                           'js/core/state.js',
  RUN_STATE:                           'js/core/state.js',
  CITATIONS:                           'js/core/state.js',
  CURRENT_RUN_ID:                      'js/core/state.js',
  CITATION_UNMAPPED_SUPPORTING_TERMS:  'js/core/state.js',
  DISC_SIM_MATRIX:                     'js/core/state.js',
  PROJECTION_STABILITY:                'js/core/state.js',
  CA_PROBE_OUTPUT:                     'js/core/state.js',
  WOLFRAM_GROUNDING_DIAGNOSTICS:       'js/core/state.js',
  AMBIGUITY_QUEUE:                     'js/core/state.js',
  EVIDENCE_FILTER_STATE:               'js/core/state.js',
  WOLFRAM_CACHE_STORAGE_ENABLED:       'js/core/state.js',
  WOLFRAM_CACHE_LAST_SAVE:             'js/core/state.js',
  WOLFRAM_QUERY_CACHE_MEM:             'js/core/state.js',
  WOLFRAM_TERM_CACHE_MEM:              'js/core/state.js',
  PROMPT_TEMPLATE_OVERRIDES:           'js/core/state.js',
  PROMPT_PREVIEW_RENDERING:            'js/core/state.js',
  ARTIFACT_STORE:                      'js/core/state.js',
  ARTIFACT_BUSY:                       'js/core/state.js',
  ACTIVE_ARTIFACT_KEY:                 'js/core/state.js',
  ACTIVE_MODAL_ID:                     'js/core/state.js',

  // ── core/refs.js ─────────────────────────────────────────────────────────────
  discInputsEl:                        'js/core/refs.js',
  setupEl:                             'js/core/refs.js',
  plotPanelEl:                         'js/core/refs.js',
  progressEl:                          'js/core/refs.js',
  vizEl:                               'js/core/refs.js',
  generatorTabBtn:                     'js/core/refs.js',
  plotTabBtn:                          'js/core/refs.js',
  TAB_ORDER:                           'js/core/refs.js',
  themeSelectGlobalEl:                 'js/core/refs.js',

  // ── core/utils.js ─────────────────────────────────────────────────────────
  RNG:                                 'js/core/utils.js',
  clampInt:                            'js/core/utils.js',
  structuredCloneSafe:                 'js/core/utils.js',
  safeHttpUrl:                         'js/core/utils.js',
  copyToClipboard:                     'js/core/utils.js',
  showToast:                           'js/ui/notifications.js',  // assigned to notifications (see below)
  hashString:                          'js/core/utils.js',
  escapeHtml:                          'js/core/utils.js',
  parseOptionalIntInput:               'js/core/utils.js',
  parseOptionalInt:                    'js/core/utils.js',

  // ── core/storage.js ───────────────────────────────────────────────────────
  loadWolframCaches:                   'js/core/storage.js',
  persistWolframCaches:                'js/core/storage.js',

  // ── ui/bootstrap.js ───────────────────────────────────────────────────────
  // (All expression/IfStatement/ForOfStatement nodes in jsLine range 164-254
  //  are routed here via BOOTSTRAP_LINE_RANGE below. Named entries for any
  //  named symbols that also land in that range follow.)
  '(expression)@164':                  'js/ui/bootstrap.js',
  '(expression)@165':                  'js/ui/bootstrap.js',
  '(expression)@166':                  'js/ui/bootstrap.js',
  '(expression)@167':                  'js/ui/bootstrap.js',
  '(expression)@168':                  'js/ui/bootstrap.js',
  '(expression)@169':                  'js/ui/bootstrap.js',
  '(expression)@170':                  'js/ui/bootstrap.js',
  '(expression)@171':                  'js/ui/bootstrap.js',
  '(expression)@172':                  'js/ui/bootstrap.js',
  '(expression)@173':                  'js/ui/bootstrap.js',
  '(expression)@174':                  'js/ui/bootstrap.js',
  '(expression)@175':                  'js/ui/bootstrap.js',
  '(IfStatement)@177':                 'js/ui/bootstrap.js',
  '(expression)@178':                  'js/ui/bootstrap.js',
  '(expression)@179':                  'js/ui/bootstrap.js',
  '(expression)@180':                  'js/ui/bootstrap.js',
  '(expression)@181':                  'js/ui/bootstrap.js',
  '(expression)@182':                  'js/ui/bootstrap.js',
  '(expression)@183':                  'js/ui/bootstrap.js',
  '(expression)@184':                  'js/ui/bootstrap.js',
  '(expression)@185':                  'js/ui/bootstrap.js',
  '(expression)@186':                  'js/ui/bootstrap.js',
  '(expression)@187':                  'js/ui/bootstrap.js',
  '(expression)@188':                  'js/ui/bootstrap.js',
  '(expression)@189':                  'js/ui/bootstrap.js',
  '(expression)@190':                  'js/ui/bootstrap.js',
  '(ForOfStatement)@191':              'js/ui/bootstrap.js',
  '(ForOfStatement)@192':              'js/ui/bootstrap.js',
  '(expression)@193':                  'js/ui/bootstrap.js',
  '(expression)@194':                  'js/ui/bootstrap.js',
  '(expression)@195':                  'js/ui/bootstrap.js',
  '(expression)@196':                  'js/ui/bootstrap.js',
  '(expression)@197':                  'js/ui/bootstrap.js',
  '(expression)@198':                  'js/ui/bootstrap.js',
  '(expression)@199':                  'js/ui/bootstrap.js',
  '(expression)@200':                  'js/ui/bootstrap.js',
  '(expression)@201':                  'js/ui/bootstrap.js',
  '(expression)@202':                  'js/ui/bootstrap.js',
  '(expression)@203':                  'js/ui/bootstrap.js',
  '(expression)@204':                  'js/ui/bootstrap.js',
  '(expression)@205':                  'js/ui/bootstrap.js',
  '(expression)@206':                  'js/ui/bootstrap.js',
  '(expression)@207':                  'js/ui/bootstrap.js',
  '(expression)@208':                  'js/ui/bootstrap.js',
  '(expression)@209':                  'js/ui/bootstrap.js',
  '(expression)@210':                  'js/ui/bootstrap.js',
  '(expression)@211':                  'js/ui/bootstrap.js',
  '(expression)@212':                  'js/ui/bootstrap.js',
  '(expression)@213':                  'js/ui/bootstrap.js',
  '(expression)@214':                  'js/ui/bootstrap.js',
  '(expression)@215':                  'js/ui/bootstrap.js',
  '(expression)@216':                  'js/ui/bootstrap.js',
  '(expression)@217':                  'js/ui/bootstrap.js',
  '(expression)@218':                  'js/ui/bootstrap.js',
  '(expression)@219':                  'js/ui/bootstrap.js',
  '(expression)@220':                  'js/ui/bootstrap.js',
  '(expression)@221':                  'js/ui/bootstrap.js',
  '(expression)@222':                  'js/ui/bootstrap.js',
  '(expression)@223':                  'js/ui/bootstrap.js',
  '(expression)@224':                  'js/ui/bootstrap.js',
  '(expression)@225':                  'js/ui/bootstrap.js',
  '(expression)@226':                  'js/ui/bootstrap.js',
  '(expression)@227':                  'js/ui/bootstrap.js',
  '(expression)@228':                  'js/ui/bootstrap.js',
  '(expression)@229':                  'js/ui/bootstrap.js',
  '(expression)@230':                  'js/ui/bootstrap.js',
  '(expression)@231':                  'js/ui/bootstrap.js',
  '(expression)@232':                  'js/ui/bootstrap.js',
  '(expression)@233':                  'js/ui/bootstrap.js',
  '(ForOfStatement)@234':              'js/ui/bootstrap.js',
  '(expression)@235':                  'js/ui/bootstrap.js',
  '(expression)@236':                  'js/ui/bootstrap.js',
  '(expression)@237':                  'js/ui/bootstrap.js',
  '(expression)@238':                  'js/ui/bootstrap.js',
  '(expression)@239a':                 'js/ui/bootstrap.js',
  '(expression)@239b':                 'js/ui/bootstrap.js',
  '(expression)@240a':                 'js/ui/bootstrap.js',
  '(expression)@240b':                 'js/ui/bootstrap.js',
  '(expression)@241':                  'js/ui/bootstrap.js',
  '(expression)@242':                  'js/ui/bootstrap.js',
  '(expression)@250':                  'js/ui/bootstrap.js',
  '(expression)@251':                  'js/ui/bootstrap.js',
  '(expression)@252':                  'js/ui/bootstrap.js',
  '(expression)@253':                  'js/ui/bootstrap.js',
  '(expression)@254':                  'js/ui/bootstrap.js',

  // ── ui/tabs.js ────────────────────────────────────────────────────────────
  switchMainTab:                       'js/ui/tabs.js',
  updateTabState:                      'js/ui/tabs.js',
  initTabAccessibility:                'js/ui/tabs.js',
  focusTabTarget:                      'js/ui/tabs.js',
  moveTabFocus:                        'js/ui/tabs.js',
  tabNameForButton:                    'js/ui/tabs.js',
  buttonForTabName:                    'js/ui/tabs.js',
  setPanelVisibility:                  'js/ui/tabs.js',
  updateZenModeUI:                     'js/ui/tabs.js',
  toggleZenMode:                       'js/ui/tabs.js',

  // ── ui/theme.js ───────────────────────────────────────────────────────────
  applyTheme:                          'js/ui/theme.js',

  // ── ui/setup-panel.js ─────────────────────────────────────────────────────
  initGenerationPanelQol:              'js/ui/setup-panel.js',
  createSetupSection:                  'js/ui/setup-panel.js',
  findDirectChildBlock:                'js/ui/setup-panel.js',
  extractSetupBlocks:                  'js/ui/setup-panel.js',
  applySetupTooltips:                  'js/ui/setup-panel.js',
  initWorkbenchJumpNav:                'js/ui/setup-panel.js',
  renderDisciplineInputs:              'js/ui/setup-panel.js',
  addProbeSpec:                        'js/ui/setup-panel.js',
  onProbeActionClick:                  'js/ui/setup-panel.js',
  getCurrentProbeSpecs:                'js/ui/setup-panel.js',
  syncCAOverrideUI:                    'js/ui/setup-panel.js',
  syncApiModeNote:                     'js/ui/setup-panel.js',
  toggleApiKey:                        'js/ui/setup-panel.js',
  clearApiKey:                         'js/ui/setup-panel.js',
  generateOrthogonalLenses:            'js/ui/setup-panel.js',

  // ── ui/resizers.js ────────────────────────────────────────────────────────
  initSidebarResizer:                  'js/ui/resizers.js',
  applySidebarWidth:                   'js/ui/resizers.js',
  clampSidebarWidth:                   'js/ui/resizers.js',
  initGenerationWorkbenchResizer:      'js/ui/resizers.js',
  applyGenerationWorkbenchLeftWidth:   'js/ui/resizers.js',
  clampGenerationWorkbenchLeftWidth:   'js/ui/resizers.js',

  // ── ui/modals.js ──────────────────────────────────────────────────────────
  openModal:                           'js/ui/modals.js',
  closeModal:                          'js/ui/modals.js',
  handleModalKeyboard:                 'js/ui/modals.js',
  focusModalEntry:                     'js/ui/modals.js',
  getFocusableElementsInModal:         'js/ui/modals.js',
  getOpenModals:                       'js/ui/modals.js',
  getActiveOpenModal:                  'js/ui/modals.js',
  isElementVisibleForFocus:            'js/ui/modals.js',
  MODAL_RETURN_FOCUS:                  'js/ui/modals.js',
  MODAL_FOCUSABLE_SELECTOR:            'js/ui/modals.js',

  // ── ui/notifications.js ───────────────────────────────────────────────────
  // showToast is declared above but pointed here
  setProbeState:                       'js/ui/notifications.js',
  updateAmbiguityQueueUIState:         'js/ui/notifications.js',

  // ── ui/prompt-preview.js ──────────────────────────────────────────────────
  refreshPromptPreview:                'js/ui/prompt-preview.js',
  applyPromptPreviewOverride:          'js/ui/prompt-preview.js',
  resetPromptPreviewOverride:          'js/ui/prompt-preview.js',
  collectRunReadinessChecks:           'js/ui/prompt-preview.js',
  updateRunReadinessSummary:           'js/ui/prompt-preview.js',
  syncPromptPreviewDiscOptions:        'js/ui/prompt-preview.js',
  getPromptPreviewDisciplineNames:     'js/ui/prompt-preview.js',
  updatePromptKindHelp:                'js/ui/prompt-preview.js',
  updatePromptOverrideSummary:         'js/ui/prompt-preview.js',
  summarizePromptOverrides:            'js/ui/prompt-preview.js',
  formatPromptOverrideDisplay:         'js/ui/prompt-preview.js',
  buildPromptParameterNarrative:       'js/ui/prompt-preview.js',

  // ── ui/ambiguity-queue-ui.js ──────────────────────────────────────────────
  renderAmbiguityQueueModal:           'js/ui/ambiguity-queue-ui.js',
  showAmbiguityQueueModal:             'js/ui/ambiguity-queue-ui.js',
  onAmbiguityQueueClick:               'js/ui/ambiguity-queue-ui.js',

  // ── ui/evidence-modal-ui.js ───────────────────────────────────────────────
  renderEvidenceCard:                  'js/ui/evidence-modal-ui.js',
  renderEvidenceCardsInto:             'js/ui/evidence-modal-ui.js',
  renderEvidenceModalContent:          'js/ui/evidence-modal-ui.js',
  showEvidenceModal:                   'js/ui/evidence-modal-ui.js',
  createEvidenceTag:                   'js/ui/evidence-modal-ui.js',
  buildEvidenceSnippetText:            'js/ui/evidence-modal-ui.js',
  getEvidenceFilterState:              'js/ui/evidence-modal-ui.js',
  setEvidenceFilterState:              'js/ui/evidence-modal-ui.js',
  citationMatchesEvidenceFilters:      'js/ui/evidence-modal-ui.js',
  citationSupportsTerm:                'js/ui/evidence-modal-ui.js',
  getCitationSupportingTerms:          'js/ui/evidence-modal-ui.js',
  detectCitationProvider:              'js/ui/evidence-modal-ui.js',
  buildWolframCitationContext:         'js/ui/evidence-modal-ui.js',
  formatWolframGroundingStatusLabel:   'js/ui/evidence-modal-ui.js',

  // ── ui/artifact-drawer-ui.js ──────────────────────────────────────────────
  setArtifactDrawer:                   'js/ui/artifact-drawer-ui.js',
  toggleArtifactDrawer:                'js/ui/artifact-drawer-ui.js',
  refreshArtifactList:                 'js/ui/artifact-drawer-ui.js',
  onArtifactSelection:                 'js/ui/artifact-drawer-ui.js',
  setExportMenu:                       'js/ui/artifact-drawer-ui.js',
  toggleExportMenu:                    'js/ui/artifact-drawer-ui.js',
  openArtifactModal:                   'js/ui/artifact-drawer-ui.js',
  renderArtifactModalEnhancements:     'js/ui/artifact-drawer-ui.js',
  artifactCanOpenWithoutRegenerate:    'js/ui/artifact-drawer-ui.js',
  openArtifact:                        'js/ui/artifact-drawer-ui.js',
  regenerateArtifact:                  'js/ui/artifact-drawer-ui.js',

  // ── pipeline/launch-expedition.js ─────────────────────────────────────────
  launchExpedition:                    'js/pipeline/launch-expedition.js',
  assignSemanticPositions:             'js/pipeline/launch-expedition.js',
  resetToSetup:                        'js/pipeline/launch-expedition.js',

  // ── pipeline/probes.js ────────────────────────────────────────────────────
  getProbeResultWithRecovery:          'js/pipeline/probes.js',
  normalizeProbeResult:                'js/pipeline/probes.js',
  buildProbeRescueResult:              'js/pipeline/probes.js',
  normalizeProbeTerm:                  'js/pipeline/probes.js',

  // ── pipeline/synthesis.js ─────────────────────────────────────────────────
  getSynthesisResultWithRecovery:      'js/pipeline/synthesis.js',
  normalizeSynthesisResult:            'js/pipeline/synthesis.js',
  normalizeSynthesisEntry:             'js/pipeline/synthesis.js',
  buildFallbackSynthesisResult:        'js/pipeline/synthesis.js',
  buildTermCoverageByDiscipline:       'js/pipeline/synthesis.js',
  jaccardFromSets:                     'js/pipeline/synthesis.js',
  coerceSynthesisDisciplines:          'js/pipeline/synthesis.js',
  disciplineIndexFromValue:            'js/pipeline/synthesis.js',
  parseSynthesisRangeMin:              'js/pipeline/synthesis.js',
  buildSynthesisCompactFallbackPrompt: 'js/pipeline/synthesis.js',
  repairSynthesisJSONWithModel:        'js/pipeline/synthesis.js',

  // ── pipeline/reruns.js ────────────────────────────────────────────────────
  rerunProbe:                          'js/pipeline/reruns.js',
  rerunSynthesis:                      'js/pipeline/reruns.js',

  // ── api/provider.js ───────────────────────────────────────────────────────
  providerFetch:                       'js/api/provider.js',
  endpointFor:                         'js/api/provider.js',
  normalizeMode:                       'js/api/provider.js',
  resolveAuth:                         'js/api/provider.js',

  // ── api/llm.js ────────────────────────────────────────────────────────────
  callLLM:                             'js/api/llm.js',
  callLLMFull:                         'js/api/llm.js',
  callLLMJSON:                         'js/api/llm.js',
  flattenContent:                      'js/api/llm.js',
  recordCall:                          'js/api/llm.js',
  readApiConfig:                       'js/api/llm.js',
  validateApiConfig:                   'js/api/llm.js',
  getQualityProfile:                   'js/api/llm.js',
  withArtifactTokenBudget:             'js/api/llm.js',

  // ── api/embeddings.js ─────────────────────────────────────────────────────
  callEmbeddings:                      'js/api/embeddings.js',
  buildEmbeddingText:                  'js/api/embeddings.js',

  // ── api/json-recovery.js ──────────────────────────────────────────────────
  extractJSON:                         'js/api/json-recovery.js',
  extractJSONLenient:                  'js/api/json-recovery.js',
  stripJsonCodeFences:                 'js/api/json-recovery.js',
  extractLooseJsonFieldValues:         'js/api/json-recovery.js',
  repairJSONWithModel:                 'js/api/json-recovery.js',
  findBalancedJsonCandidates:          'js/api/json-recovery.js',
  escapeNewlinesInsideJsonStrings:     'js/api/json-recovery.js',
  sanitizeJsonCandidate:               'js/api/json-recovery.js',
  buildJsonParseCandidates:            'js/api/json-recovery.js',
  parseJsonFromModelText:              'js/api/json-recovery.js',
  decodeLooseJsonString:               'js/api/json-recovery.js',

  // ── grounding/wolfram-cache.js ────────────────────────────────────────────
  normalizeWolframCacheKey:            'js/grounding/wolfram-cache.js',
  normalizeWolframTermCacheKey:        'js/grounding/wolfram-cache.js',
  wolframCacheNow:                     'js/grounding/wolfram-cache.js',
  buildWolframTermCacheKey:            'js/grounding/wolfram-cache.js',
  enforceWolframCacheLimit:            'js/grounding/wolfram-cache.js',
  pruneExpiredWolframCache:            'js/grounding/wolfram-cache.js',
  getWolframQueryCache:                'js/grounding/wolfram-cache.js',
  setWolframQueryCache:                'js/grounding/wolfram-cache.js',
  getWolframTermCache:                 'js/grounding/wolfram-cache.js',
  setWolframTermCache:                 'js/grounding/wolfram-cache.js',

  // ── grounding/wolfram-parse.js ────────────────────────────────────────────
  extractWolframNormalized:            'js/grounding/wolfram-parse.js',
  compactWolframText:                  'js/grounding/wolfram-parse.js',
  wolframPodTitleScore:                'js/grounding/wolfram-parse.js',
  extractWolframListValues:            'js/grounding/wolfram-parse.js',
  isWolframLowSignalText:              'js/grounding/wolfram-parse.js',
  fetchWolframJSON:                    'js/grounding/wolfram-parse.js',
  extractWolframStructured:            'js/grounding/wolfram-parse.js',
  selectWolframSnippetFromParsed:      'js/grounding/wolfram-parse.js',
  buildNoPlaintextReasons:             'js/grounding/wolfram-parse.js',
  extractWolframPlaintext:             'js/grounding/wolfram-parse.js',
  resolveWolframChosenPod:             'js/grounding/wolfram-parse.js',
  scoreWolframSnippet:                 'js/grounding/wolfram-parse.js',
  serializeWolframParsed:              'js/grounding/wolfram-parse.js',
  resolveWolframTemplateToken:         'js/grounding/wolfram-parse.js',
  wolframPublicInputUrl:               'js/grounding/wolfram-parse.js',
  sanitizeWolframToken:                'js/grounding/wolfram-parse.js',
  canonicalizeWolframLabelForQuery:    'js/grounding/wolfram-parse.js',

  // ── grounding/wolfram-score.js ────────────────────────────────────────────
  interpretationLooksGeneric:          'js/grounding/wolfram-score.js',
  computeGenericInterpretationHotspotAudit: 'js/grounding/wolfram-score.js',
  renderGenericInterpretationHotspotAudit:  'js/grounding/wolfram-score.js',
  buildGroundingHealthWarnings:        'js/grounding/wolfram-score.js',
  isLikelyDictionaryOnlyGroundingText: 'js/grounding/wolfram-score.js',
  computeGroundingStats:               'js/grounding/wolfram-score.js',
  computeRunGroundingStats:            'js/grounding/wolfram-score.js',
  computeSourceTypeBreakdown:          'js/grounding/wolfram-score.js',
  normalizeGroundingAggressiveness:    'js/grounding/wolfram-score.js',
  clampGroundingSnippetScore:          'js/grounding/wolfram-score.js',
  parseGroundingSnippetScoreInput:     'js/grounding/wolfram-score.js',
  resolveGroundingPolicy:              'js/grounding/wolfram-score.js',
  evaluateGroundingApplication:        'js/grounding/wolfram-score.js',
  isAbstractConceptPhrase:             'js/grounding/wolfram-score.js',
  isAbstractNameCollisionTarget:       'js/grounding/wolfram-score.js',
  looksNameLikeInterpretation:         'js/grounding/wolfram-score.js',
  resolveScoringComponent:             'js/grounding/wolfram-score.js',
  classifyWolframResolvedCategory:     'js/grounding/wolfram-score.js',
  evaluateGroundingCategoryMismatch:   'js/grounding/wolfram-score.js',
  labelContentTokens:                  'js/grounding/wolfram-score.js',
  isTitleCaseCompositeLabel:           'js/grounding/wolfram-score.js',
  isCompositeSyntheticTermLabel:       'js/grounding/wolfram-score.js',
  hasExactConceptPhraseMatch:          'js/grounding/wolfram-score.js',
  hasHighAlignmentConceptMatch:        'js/grounding/wolfram-score.js',
  applySingleWordDriftGuard:           'js/grounding/wolfram-score.js',
  applyWarningAssumptionRiskGuard:     'js/grounding/wolfram-score.js',
  applyCompositeTermAppendGuard:       'js/grounding/wolfram-score.js',
  expectedCategoriesForEntityType:     'js/grounding/wolfram-score.js',
  interpretationTypeLooksUnrelated:    'js/grounding/wolfram-score.js',
  hasSuspiciousDomainMarkerMismatch:   'js/grounding/wolfram-score.js',
  evaluateSuspiciousAcceptedGrounding: 'js/grounding/wolfram-score.js',
  applyGroundingCategoryMismatchGuard: 'js/grounding/wolfram-score.js',
  applySuspiciousAcceptanceAuditPass:  'js/grounding/wolfram-score.js',
  normalizeWolframCacheStatus:         'js/grounding/wolfram-score.js',
  recordWolframAuditEvent:             'js/grounding/wolfram-score.js',

  // ── grounding/wolfram-grounding.js ────────────────────────────────────────
  groundProbeTermsWithWolfram:         'js/grounding/wolfram-grounding.js',
  buildWolframEntityRef:               'js/grounding/wolfram-grounding.js',
  normalizeWolframAssumptionText:      'js/grounding/wolfram-grounding.js',
  normalizeSourceType:                 'js/grounding/wolfram-grounding.js',
  waTermStatusLabel:                   'js/grounding/wolfram-grounding.js',
  waTermStatusColor:                   'js/grounding/wolfram-grounding.js',
  deriveWolframDomainHintFromDiscName: 'js/grounding/wolfram-grounding.js',
  isComputationalMathLikeTerm:         'js/grounding/wolfram-grounding.js',
  buildWolframEntityQueryAttempts:     'js/grounding/wolfram-grounding.js',
  buildWolframGroundingCitation:       'js/grounding/wolfram-grounding.js',
  setTermGroundingEligibility:         'js/grounding/wolfram-grounding.js',
  dedupeCitations:                     'js/grounding/wolfram-grounding.js',
  buildWolframLayerTextForPolicy:      'js/grounding/wolfram-grounding.js',
  recordWolframGroundingDiagnostic:    'js/grounding/wolfram-grounding.js',
  normalizeGroundingEligibility:       'js/grounding/wolfram-grounding.js',
  defaultGroundingBlock:               'js/grounding/wolfram-grounding.js',
  normalizeGroundingStatus:            'js/grounding/wolfram-grounding.js',
  normalizeGroundingBlock:             'js/grounding/wolfram-grounding.js',
  mergeGroundingBlocks:                'js/grounding/wolfram-grounding.js',
  normalizeWolframEntityCandidate:     'js/grounding/wolfram-grounding.js',

  // ── grounding/ambiguity-queue.js ──────────────────────────────────────────
  ambiguityQueueKey:                   'js/grounding/ambiguity-queue.js',
  getAmbiguityReasonsFromDiagnostic:   'js/grounding/ambiguity-queue.js',
  normalizeAmbiguityQueueItem:         'js/grounding/ambiguity-queue.js',
  normalizeAmbiguitySeverity:          'js/grounding/ambiguity-queue.js',
  computeAmbiguityPriority:            'js/grounding/ambiguity-queue.js',
  sortAmbiguityQueueInPlace:           'js/grounding/ambiguity-queue.js',
  getPendingAmbiguityCount:            'js/grounding/ambiguity-queue.js',
  upsertAmbiguityQueueItem:            'js/grounding/ambiguity-queue.js',
  upsertAmbiguityFromDiagnostic:       'js/grounding/ambiguity-queue.js',
  rebuildAmbiguityQueueFromDiagnostics: 'js/grounding/ambiguity-queue.js',
  formatAmbiguityReason:               'js/grounding/ambiguity-queue.js',
  findTermForAmbiguityItem:            'js/grounding/ambiguity-queue.js',
  applyAmbiguityDecisionToTerm:        'js/grounding/ambiguity-queue.js',
  buildAmbiguityRetryTemplates:        'js/grounding/ambiguity-queue.js',
  getAmbiguityRetryTemplate:           'js/grounding/ambiguity-queue.js',
  retryAmbiguityWithQuery:             'js/grounding/ambiguity-queue.js',
  retryAmbiguityWithTemplate:          'js/grounding/ambiguity-queue.js',
  retryAmbiguityWithCustomQuery:       'js/grounding/ambiguity-queue.js',

  // ── domain/terms.js ───────────────────────────────────────────────────────
  buildTerms:                          'js/domain/terms.js',
  addRawTerm:                          'js/domain/terms.js',
  mergeRawTerms:                       'js/domain/terms.js',
  mergeType:                           'js/domain/terms.js',
  pickBetterLabel:                     'js/domain/terms.js',
  mergeDescription:                    'js/domain/terms.js',
  defaultDescriptionLayers:            'js/domain/terms.js',
  inferDescriptionSourceFromLayers:    'js/domain/terms.js',
  computeDisplayDescriptionFromLayers: 'js/domain/terms.js',
  normalizeTermDescriptions:           'js/domain/terms.js',
  mergeTermDescriptions:               'js/domain/terms.js',
  applyDisplayDescriptionForTerm:      'js/domain/terms.js',
  mergeWolframDisplayMode:             'js/domain/terms.js',
  normalizeWolframDisplayMode:         'js/domain/terms.js',
  buildTermsForReplicationRun:         'js/domain/terms.js',
  normalizeLabel:                      'js/domain/terms.js',
  makeAbbr:                            'js/domain/terms.js',

  // ── domain/aliases.js ─────────────────────────────────────────────────────
  toCanonicalKey:                      'js/domain/aliases.js',
  tokenSet:                            'js/domain/aliases.js',
  jaccardSimilarity:                   'js/domain/aliases.js',
  aliasSimilarityScore:                'js/domain/aliases.js',
  matchTermFromAliasCandidate:         'js/domain/aliases.js',
  buildTermAliasIndex:                 'js/domain/aliases.js',
  mapSupportingTermsWithAliases:       'js/domain/aliases.js',

  // ── domain/citations.js ───────────────────────────────────────────────────
  collectCitations:                    'js/domain/citations.js',
  normalizeCitation:                   'js/domain/citations.js',
  upsertCitationEntry:                 'js/domain/citations.js',
  getLinkedCitationsForTerm:           'js/domain/citations.js',
  normalizeAliasMappingEntry:          'js/domain/citations.js',
  normalizeProvenanceEntry:            'js/domain/citations.js',
  mergeDescriptionProvenance:          'js/domain/citations.js',
  mergeDescriptionSource:              'js/domain/citations.js',
  sourceTypeLabel:                     'js/domain/citations.js',
  dedupeCasefold:                      'js/domain/citations.js',
  confidenceRank:                      'js/domain/citations.js',
  normalizeConfidenceLevel:            'js/domain/citations.js',
  betterConfidence:                    'js/domain/citations.js',

  // ── domain/grounding-status.js ────────────────────────────────────────────
  getTermGroundingOutcome:             'js/domain/grounding-status.js',
  getNodeGroundingStatus:              'js/domain/grounding-status.js',
  termGroundingOutcomeLabel:           'js/domain/grounding-status.js',
  termGroundingOutcomeColor:           'js/domain/grounding-status.js',
  isLocalDefinedTerm:                  'js/domain/grounding-status.js',
  isWolframGroundingCitation:          'js/domain/grounding-status.js',
  getWolframCitationsForTerm:          'js/domain/grounding-status.js',
  getResearchCitationsForTerm:         'js/domain/grounding-status.js',
  computeTermRelevanceScore:           'js/domain/grounding-status.js',
  computeTermEvidenceSupportScore:     'js/domain/grounding-status.js',
  termScoreBand:                       'js/domain/grounding-status.js',
  getTermGroundingReasonHints:         'js/domain/grounding-status.js',
  deriveWaGroundingStatusKey:          'js/domain/grounding-status.js',
  deriveTermStateBadge:                'js/domain/grounding-status.js',
  getTermSignalModel:                  'js/domain/grounding-status.js',
  refreshTermSignalFields:             'js/domain/grounding-status.js',
  getNodeGroundingConfidenceScore:     'js/domain/grounding-status.js',
  TERM_GROUNDING_OUTCOME_META:         'js/domain/grounding-status.js',
  WA_TERM_STATUS_META:                 'js/domain/grounding-status.js',
  WA_ACCEPTED_GROUNDING_STATUSES:      'js/domain/grounding-status.js',
  WA_GRAPH_STATUS_META:                'js/domain/grounding-status.js',
  KNOWN_RULE_CLASSES:                  'js/domain/grounding-status.js',
  getLLMProbeCount:                    'js/domain/grounding-status.js',

  // ── domain/run-metadata.js ────────────────────────────────────────────────
  computeRunId:                        'js/domain/run-metadata.js',
  safeConfigForRun:                    'js/domain/run-metadata.js',
  buildRunSnapshot:                    'js/domain/run-metadata.js',
  serializeTermForRun:                 'js/domain/run-metadata.js',
  applyRenameMapToResults:             'js/domain/run-metadata.js',
  applySecondPassCleanup:              'js/domain/run-metadata.js',
  getRunFingerprint:                   'js/domain/run-metadata.js',

  // ── ca/automata.js ────────────────────────────────────────────────────────
  simulateElementaryCA:                'js/ca/automata.js',
  normalizeOddWidth:                   'js/ca/automata.js',
  estimateWolframRuleClass:            'js/ca/automata.js',
  resolveCARuleFallbackCounts:         'js/ca/automata.js',
  computeCARuleFallbackHash:           'js/ca/automata.js',
  takeWithWrap:                        'js/ca/automata.js',
  deriveRuleFromSimilarityMatrix:      'js/ca/automata.js',
  deriveWidthFromTermCount:            'js/ca/automata.js',
  deriveStepsFromSynthesisDepth:       'js/ca/automata.js',
  buildInitialRowFromProbes:           'js/ca/automata.js',
  isRunDerivedCAOutput:                'js/ca/automata.js',

  // ── ca/metrics.js ─────────────────────────────────────────────────────────
  computeAutomataMetrics:              'js/ca/metrics.js',
  maxContiguousAliveRun:               'js/ca/metrics.js',
  trajectoryLinearRegressionSlope:     'js/ca/metrics.js',
  countMeanZeroCrossings:              'js/ca/metrics.js',
  classifyTrajectoryTrend:             'js/ca/metrics.js',
  computeMetricTrajectories:           'js/ca/metrics.js',
  medianOfNumbers:                     'js/ca/metrics.js',
  modeValue:                           'js/ca/metrics.js',

  // ── ca/derive-ca.js ───────────────────────────────────────────────────────
  deriveCAFromRun:                     'js/ca/derive-ca.js',
  buildCATermsFromMetrics:             'js/ca/derive-ca.js',
  appendDerivedCATermsToTerms:         'js/ca/derive-ca.js',
  buildRunDerivedCommentary:           'js/ca/derive-ca.js',
  extractWolframClassNumber:           'js/ca/derive-ca.js',
  formatWolframClassForReplication:    'js/ca/derive-ca.js',
  summarizeReplicationCAFingerprints:  'js/ca/derive-ca.js',
  formatReplicationCAFingerprintSection: 'js/ca/derive-ca.js',
  deriveReplicationCAFingerprint:      'js/ca/derive-ca.js',

  // ── ca/render-ca-panel.js ─────────────────────────────────────────────────
  renderCAPanel:                       'js/ca/render-ca-panel.js',
  renderAutomataDataUrl:               'js/ca/render-ca-panel.js',
  buildDerivationDetailHTML:           'js/ca/render-ca-panel.js',
  renderTrajectoryChart:               'js/ca/render-ca-panel.js',
  drawCATrajectoryMiniChart:           'js/ca/render-ca-panel.js',

  // ── embedding/vector-math.js ──────────────────────────────────────────────
  normalizeEmbeddingVector:            'js/embedding/vector-math.js',
  cosineDistance:                      'js/embedding/vector-math.js',
  averageVector:                       'js/embedding/vector-math.js',
  euclid3:                             'js/embedding/vector-math.js',
  averagePoint3:                       'js/embedding/vector-math.js',
  averageNumbers:                      'js/embedding/vector-math.js',
  normalize3:                          'js/embedding/vector-math.js',

  // ── embedding/umap-loader.js ──────────────────────────────────────────────
  loadUMAPModule:                      'js/embedding/umap-loader.js',

  // ── embedding/projection.js ───────────────────────────────────────────────
  projectVectorsTo3D:                  'js/embedding/projection.js',
  randomProjection3D:                  'js/embedding/projection.js',
  normalizePointCloud:                 'js/embedding/projection.js',
  applyFallbackPositions:              'js/embedding/projection.js',

  // ── embedding/diagnostics.js ──────────────────────────────────────────────
  computeProjectionStability:          'js/embedding/diagnostics.js',
  renderEmbeddingDiagnostics:          'js/embedding/diagnostics.js',
  computeDiscSimilarityMatrix:         'js/embedding/diagnostics.js',
  computeDiscSimilarityMatrixForTerms: 'js/embedding/diagnostics.js',
  computeRunDiscSimilarityMatrixForTerms: 'js/embedding/diagnostics.js',
  computeDiscCentroidsFromVectors:     'js/embedding/diagnostics.js',
  computeDiscCentroidsFromPoints:      'js/embedding/diagnostics.js',
  buildDiscNeighborMap:                'js/embedding/diagnostics.js',
  neighborOverlap:                     'js/embedding/diagnostics.js',

  // ── plot/plot-render.js ───────────────────────────────────────────────────
  renderPlot:                          'js/plot/plot-render.js',
  showViz:                             'js/plot/plot-render.js',
  CONFIG:                              'js/plot/plot-render.js',

  // ── plot/plot-layout.js ───────────────────────────────────────────────────
  getPlotLayout:                       'js/plot/plot-layout.js',

  // ── plot/plot-overlays.js ─────────────────────────────────────────────────
  appendGroundingOverlayTraces:        'js/plot/plot-overlays.js',
  buildSurface:                        'js/plot/plot-overlays.js',
  buildTraces:                         'js/plot/plot-overlays.js',
  markerSizeByCentrality:              'js/plot/plot-overlays.js',
  getGroundingConfidenceRank:          'js/plot/plot-overlays.js',
  groundingColorForTerm:               'js/plot/plot-overlays.js',
  getEmergentRingColor:                'js/plot/plot-overlays.js',
  hasWolframGrounding:                 'js/plot/plot-overlays.js',
  isUnresolvedGrounding:               'js/plot/plot-overlays.js',
  clamp01:                             'js/plot/plot-overlays.js',
  clampSurfaceOpacity:                 'js/plot/plot-overlays.js',
  fallbackDirection:                   'js/plot/plot-overlays.js',
  computeDisciplineAnchors:            'js/plot/plot-overlays.js',

  // ── plot/term-detail.js ───────────────────────────────────────────────────
  buildTermDescriptionDetail:          'js/plot/term-detail.js',
  onPlotClick:                         'js/plot/term-detail.js',
  formatProvenanceLine:                'js/plot/term-detail.js',
  summarizeWhyNodeExists:              'js/plot/term-detail.js',
  resolveChosenWolframQuery:           'js/plot/term-detail.js',
  showTermDetail:                      'js/plot/term-detail.js',

  // ── plot/sidebar.js ───────────────────────────────────────────────────────
  buildSidebar:                        'js/plot/sidebar.js',
  buildStats:                          'js/plot/sidebar.js',
  renderNodeFilterResults:             'js/plot/sidebar.js',
  initNodeFilterControls:              'js/plot/sidebar.js',
  clearNodeFilters:                    'js/plot/sidebar.js',
  getNodeFilterState:                  'js/plot/sidebar.js',
  sortNodes:                           'js/plot/sidebar.js',
  getVisibleNodeTerms:                 'js/plot/sidebar.js',
  matchesNodeFilters:                  'js/plot/sidebar.js',
  fuzzyLabelMatch:                     'js/plot/sidebar.js',
  renderGroundingLegend:               'js/plot/sidebar.js',

  // ── artifacts/artifact-store.js ───────────────────────────────────────────
  initArtifactStore:                   'js/artifacts/artifact-store.js',
  setArtifactReady:                    'js/artifacts/artifact-store.js',
  markArtifactsStale:                  'js/artifacts/artifact-store.js',
  updateDerivedArtifactsReady:         'js/artifacts/artifact-store.js',
  artifactStatusBadge:                 'js/artifacts/artifact-store.js',
  updateArtifactProgress:              'js/artifacts/artifact-store.js',
  ARTIFACT_DEFS:                       'js/artifacts/artifact-store.js',
  setArtifactBusy:                     'js/artifacts/artifact-store.js',
  withArtifactTask:                    'js/artifacts/artifact-store.js',
  syncArtifactStoreFromRun:            'js/artifacts/artifact-store.js',
  buildRawTermsArtifact:               'js/artifacts/artifact-store.js',
  buildEvidenceArtifact:               'js/artifacts/artifact-store.js',

  // ── artifacts/artifact-generators.js ─────────────────────────────────────
  generateDeepReport:                  'js/artifacts/artifact-generators.js',
  generateClaimsLedger:                'js/artifacts/artifact-generators.js',
  formatClaimsLedger:                  'js/artifacts/artifact-generators.js',
  generateOutlineFromMap:              'js/artifacts/artifact-generators.js',
  runRedTeamPass:                      'js/artifacts/artifact-generators.js',
  runReplication:                      'js/artifacts/artifact-generators.js',
  copyReportText:                      'js/artifacts/artifact-generators.js',
  copyClaimsText:                      'js/artifacts/artifact-generators.js',
  copyOutlineText:                     'js/artifacts/artifact-generators.js',
  copyCritiqueText:                    'js/artifacts/artifact-generators.js',
  showRawNodeList:                     'js/artifacts/artifact-generators.js',
  copyActiveArtifact:                  'js/artifacts/artifact-generators.js',
  downloadActiveArtifact:              'js/artifacts/artifact-generators.js',
  copyArtifact:                        'js/artifacts/artifact-generators.js',
  downloadArtifact:                    'js/artifacts/artifact-generators.js',
  generateDeepReportArtifact:          'js/artifacts/artifact-generators.js',
  generateClaimsArtifact:              'js/artifacts/artifact-generators.js',
  generateOutlineArtifact:             'js/artifacts/artifact-generators.js',
  generateRedTeamArtifact:             'js/artifacts/artifact-generators.js',
  generateReplicationArtifact:         'js/artifacts/artifact-generators.js',
  generateMarkdownArtifact:            'js/artifacts/artifact-generators.js',
  artifactToCopyText:                  'js/artifacts/artifact-generators.js',
  artifactFilenameBase:                'js/artifacts/artifact-generators.js',
  buildReplicationCitationsFromProbeResults: 'js/artifacts/artifact-generators.js',

  // ── artifacts/exporters.js ────────────────────────────────────────────────
  exportRunToFile:                     'js/artifacts/exporters.js',
  exportMarkdownReport:                'js/artifacts/exporters.js',
  exportFigure:                        'js/artifacts/exporters.js',
  downloadTextFile:                    'js/artifacts/exporters.js',
  downloadBlob:                        'js/artifacts/exporters.js',
  exportArtifactBundle:                'js/artifacts/exporters.js',

  // ── artifacts/wa-graph-export.js ──────────────────────────────────────────
  waGraphStatusLabel:                  'js/artifacts/wa-graph-export.js',
  waGraphStatusColor:                  'js/artifacts/wa-graph-export.js',
  hexToRgbaColor:                      'js/artifacts/wa-graph-export.js',
  normalizeWAGraphLabel:               'js/artifacts/wa-graph-export.js',
  resolveWAGraphOutcomeBucket:         'js/artifacts/wa-graph-export.js',
  buildWAGroundingGraphData:           'js/artifacts/wa-graph-export.js',
  buildWAGroundingGraphText:           'js/artifacts/wa-graph-export.js',
  buildWAGroundingGraphHTML:           'js/artifacts/wa-graph-export.js',
  buildWAGroundingGraphArtifact:       'js/artifacts/wa-graph-export.js',
  renderWAGroundingGraphSankey:        'js/artifacts/wa-graph-export.js',
  buildWAGraphReadyNodeExport:         'js/artifacts/wa-graph-export.js',
  buildWAGraphReadyEdgeExport:         'js/artifacts/wa-graph-export.js',
  buildWAGraphReadyWLSource:           'js/artifacts/wa-graph-export.js',
  buildWAGraphReadyExportData:         'js/artifacts/wa-graph-export.js',
  exportWAGraphReadyArtifacts:         'js/artifacts/wa-graph-export.js',

  // ── io/import-export-run.js ───────────────────────────────────────────────
  importRunFromFile:                   'js/io/import-export-run.js',
  hydrateRunFromImport:                'js/io/import-export-run.js',
  setSelectValuePreserveOption:        'js/io/import-export-run.js',

  // ── prompt/prompt-system.js ───────────────────────────────────────────────
  PROMPT_OVERRIDE_KINDS:               'js/prompt/prompt-system.js',
  PROMPT_KIND_META:                    'js/prompt/prompt-system.js',
  resolvePromptBundleWithOverrides:    'js/prompt/prompt-system.js',
  getEffectivePromptBundle:            'js/prompt/prompt-system.js',
  normalizePromptOverrideKind:         'js/prompt/prompt-system.js',
  normalizePromptOverrideDisciplineKey: 'js/prompt/prompt-system.js',
  buildPromptOverrideKey:              'js/prompt/prompt-system.js',
  getPromptOverride:                   'js/prompt/prompt-system.js',
  setPromptOverride:                   'js/prompt/prompt-system.js',
  clearPromptOverride:                 'js/prompt/prompt-system.js',
  interpolatePromptTemplate:           'js/prompt/prompt-system.js',
  getPromptKindMeta:                   'js/prompt/prompt-system.js',
  getPromptTemplateVars:               'js/prompt/prompt-system.js',
  buildDefaultPromptBundle:            'js/prompt/prompt-system.js',
  buildPromptPreviewArtifactPrompts:   'js/prompt/prompt-system.js',
  buildLensGenerationPrompt:           'js/prompt/prompt-system.js',

  // ── prompt/prompt-builders.js ─────────────────────────────────────────────
  buildProbeUserPrompt:                'js/prompt/prompt-builders.js',
  buildSynthesisPrompt:                'js/prompt/prompt-builders.js',
  buildRedTeamPrompt:                  'js/prompt/prompt-builders.js',
  buildProbeSystemPrompt:              'js/prompt/prompt-builders.js',
  buildProbeCompactFallbackPrompt:     'js/prompt/prompt-builders.js',
  appendPromptMadLibBlock:             'js/prompt/prompt-builders.js',
  sanitizePromptMadLib:                'js/prompt/prompt-builders.js',
  buildPromptMadLibNotes:              'js/prompt/prompt-builders.js',

};

// Expression-statement nodes (event listeners, init calls) → bootstrap
// These are identified by jsLine range 164-254, not by name.
// The decompose script routes all ExpressionStatement/IfStatement/ForOfStatement
// top-level nodes in this range to js/ui/bootstrap.js automatically.
export const BOOTSTRAP_LINE_RANGE = { start: 164, end: 999 };
